-- Health Intel cache — stores pre-generated Opus synthesis per tab.
--
-- The Health Intelligence tab in Pulse shows LLM-synthesized content rather
-- than raw data: condition status, flags, dietary guidance, Rx review, next
-- visit prep, and a chronology. Each tab is generated by Claude Opus against
-- the full health payload (labs + meds + conditions + body areas) and then
-- cached here so the UI loads instantly.
--
-- Regeneration is triggered after a health data import or on demand via a
-- POST endpoint. The cache row is the single source of truth for the UI.

CREATE TABLE IF NOT EXISTS health_intel (
  tab           TEXT PRIMARY KEY,
  content       TEXT NOT NULL,
  generated_at  TEXT NOT NULL DEFAULT (datetime('now')),
  model         TEXT NOT NULL DEFAULT '',
  input_tokens  INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0
);
