-- Generated per-subject health prose cache (st_3ca30b26).
--
-- Governing precedent: health_intel (migrations 014 + 123). Model-authored prose
-- cached in a row, invalidated by a content hash over the exact generation input,
-- regenerated by the owner-triggered recalc job. Prose columns only -- no generated
-- output ever becomes a marker value, reference range, target, or trend score.
--
-- Deliberately NOT health_markers.description / .recommendations: those feed
-- computeTrend's +10 score term (apps/health/chart.js), sit inside
-- healthMarkerOntologySignature (routes/health.js), and fire the migration-120
-- AFTER UPDATE trigger that moves the Opus intel staleness clock. Writing the
-- generated prose there would silently reorder every chart this story just fixed.
--
-- scope: 'marker' (subject_id = canonical marker id) or 'area' (subject_id =
-- bodyAreaMap key). Enforced in lib/health-marker-copy.js, NOT as a CHECK:
-- SQLite cannot drop a CHECK without a full table rebuild.
--
-- No secondary index: the only read is a full scan of at most 62 rows per
-- payload build.

CREATE TABLE IF NOT EXISTS health_marker_copy (
  scope            TEXT    NOT NULL,
  subject_id       TEXT    NOT NULL,
  definition       TEXT    NOT NULL DEFAULT '',
  trend            TEXT    NOT NULL DEFAULT '',
  action           TEXT    NOT NULL DEFAULT '',
  narrative        TEXT    NOT NULL DEFAULT '',
  omitted          INTEGER NOT NULL DEFAULT 0,
  omitted_reason   TEXT    NOT NULL DEFAULT '',
  input_signature  TEXT    NOT NULL DEFAULT '',
  model            TEXT    NOT NULL DEFAULT '',
  generated_at     TEXT    NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (scope, subject_id)
);
