window.RobotDojoAccountApp = {
  id: 'account',
  name: 'Accounts',
  icon: 'settings',
  nav: [
    { key: 'how-to', icon: 'robotdojo-logo', label: 'How To Robot' },
    { key: 'general', icon: 'admin_panel_settings', label: 'Admin' },
    { key: 'integrations', icon: 'electrical_services', label: 'Integrations' },
    { divider: true },
    { key: 'agents', icon: 'smart_toy', label: 'Agents' },
    { key: 'skills', icon: 'construction', label: 'Skills' },
    { key: 'you', icon: 'person', label: 'You' },
    { divider: true },
    { key: 'shortcuts', icon: 'keyboard', label: 'Shortcuts' },
  ],
  aliases: {
    howto: 'how-to',
    'how-to-robot': 'how-to',
    admin: 'general',
    usage: 'integrations',
    'remote-access': 'general',
    reporting: 'how-to',
    invite: 'how-to',
    'feature-request': 'how-to',
    'feature-requests': 'how-to',
    referrals: 'how-to',
    delete: 'general',
  },
};
