/**
 * Health Intelligence — model-powered synthesis for the Pulse Intel tab.
 *
 * Insights (one document) is generated by
 * composing the full health context (latest labs + active meds + conditions +
 * body-area context + marker trends) and feeding it to the configured model with a
 * tab-specific system prompt. Results are cached in the `health_intel` table
 * so the UI loads instantly; regeneration is explicit (after import or via a
 * dedicated endpoint) rather than lazy-on-read to avoid model costs on
 * every page view.
 *
 * Architecture mirrors dojo's lib/health-intel.js but rebuilt against the
 * robotdojo primitives (getAnthropicClient, the robotdojo health schema,
 * and the migration framework in lib/db.js). No dependency on dojo code.
 */

// INTELLIGENCE_TIER: synthesis — model-powered synthesis of the Pulse Intel
// tabs; the generated prose is persisted and read back by the health UI.
export const INTELLIGENCE_TIER = 'synthesis';

import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import db from './db.js';
import { estimateCostCents } from './compute-tier.js';
import { llmCreate } from './llm-gateway.js';
import { modelFor } from './model-lane.js';
import config from './config.js';
import { buildAppMemoryContext } from './app-memory-context.js';
import { USER_CONTEXTS_DIR, USER_DATABASES_DIR, USER_MEMORY_DIR, USER_WORKBENCHES_DIR } from './robotdojo-paths.js';
import { listDataPointsGroupedByMarker } from './health-queries.js';
import { enrichHealthMarker } from './health-marker-metadata.js';
import { listEffectiveMedicationsRaw } from './health-medications.js';
import { regenerateHealthMarkerCopy } from './health-marker-copy.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const MAX_OUTPUT_TOKENS = {
  insights: 3600,
  intel: 7200,
  diet: 8200,
  rx: 7200,
  nextvisit: 5600,
  chronology: 8200,
};

const CONTEXT_PROFILES = {
  insights: { memoryChars: 1200, topicChars: 3600, ownerHistoryChars: 8000, historicalChars: 9000, dataQualityChars: 3600, labLimit: 70, labChars: 5200, nonLabLimit: 35, nonLabChars: 2800, trendLimit: 70, trendChars: 5000, timelineChars: 5200, foodChars: 7000 },
  intel: { memoryChars: 1200, topicChars: 3600, ownerHistoryChars: 8000, historicalChars: 11000, dataQualityChars: 5200, labLimit: 80, labChars: 6200, nonLabLimit: 45, nonLabChars: 3600, trendLimit: 80, trendChars: 6200, timelineChars: 7000 },
  diet: { memoryChars: 1200, topicChars: 4200, ownerHistoryChars: 10000, historicalChars: 12000, dataQualityChars: 3600, labLimit: 70, labChars: 5200, nonLabLimit: 35, nonLabChars: 2800, trendLimit: 70, trendChars: 5000, foodChars: 9000 },
  rx: { memoryChars: 1200, topicChars: 4000, ownerHistoryChars: 8000, historicalChars: 12000, dataQualityChars: 5200, labLimit: 90, labChars: 6400, nonLabLimit: 35, nonLabChars: 2800, trendLimit: 90, trendChars: 6400, timelineChars: 5200 },
  nextvisit: { memoryChars: 1200, topicChars: 4200, ownerHistoryChars: 9000, historicalChars: 12500, dataQualityChars: 6200, labLimit: 100, labChars: 7200, nonLabLimit: 40, nonLabChars: 3200, trendLimit: 100, trendChars: 7000, timelineChars: 6200 },
  chronology: { memoryChars: 1200, topicChars: 4200, ownerHistoryChars: 15000, historicalChars: 18000, dataQualityChars: 4800, labLimit: 120, labChars: 8200, trendLimit: 120, trendChars: 8200, timelineChars: 16000 },
};

function healthIntelModel() {
  if (process.env.ROBOTDOJO_HEALTH_INTEL_MODEL) return process.env.ROBOTDOJO_HEALTH_INTEL_MODEL;
  return modelFor('best');
}
const HEALTH_INTEL_TIMEOUT_MS = Number.isFinite(Number(process.env.ROBOTDOJO_HEALTH_INTEL_TIMEOUT_MS))
  && Number(process.env.ROBOTDOJO_HEALTH_INTEL_TIMEOUT_MS) > 0
  ? Number(process.env.ROBOTDOJO_HEALTH_INTEL_TIMEOUT_MS)
  : 300_000;
const HEALTH_INTEL_CONTEXT_UPDATED_AT = '2026-06-29 15:30:00';

export const TABS = ['insights'];
export const LEGACY_TABS = ['intel', 'diet', 'rx', 'nextvisit', 'chronology'];

export function resolveIntelTab(tab) {
  if (TABS.includes(tab)) return tab;
  if (LEGACY_TABS.includes(tab) || tab === 'all') return 'insights';
  return null;
}

// ─── UI config loader ─────────────────────────────────────────────────────

const HEALTH_UI_CONFIG_PATH = resolve(__dirname, '..', 'config', 'health-ui.json');
let _uiConfig = null;
let _uiConfigMtimeMs = null;
export function getUIConfig() {
  try {
    const mtimeMs = statSync(HEALTH_UI_CONFIG_PATH).mtimeMs;
    if (_uiConfig && _uiConfigMtimeMs === mtimeMs) return _uiConfig;
    _uiConfig = JSON.parse(readFileSync(HEALTH_UI_CONFIG_PATH, 'utf-8'));
    _uiConfigMtimeMs = mtimeMs;
  } catch (err) {
    console.warn('[health-intel] health-ui.json unavailable:', err.message);
    _uiConfig = { conditionGroups: [], rxGroups: [], bodyAreaMap: {}, rxMarkerMap: {} };
    _uiConfigMtimeMs = null;
  }
  return _uiConfig;
}

let _foodOntology = null;
const HEALTH_FOOD_ONTOLOGY_PATH = resolve(__dirname, '..', 'config', 'health-food-ontology.json');
export function getFoodOntology() {
  if (_foodOntology) return _foodOntology;
  try {
    _foodOntology = JSON.parse(readFileSync(HEALTH_FOOD_ONTOLOGY_PATH, 'utf-8'));
  } catch (err) {
    console.warn('[health-intel] health-food-ontology.json unavailable:', err.message);
    _foodOntology = null;
  }
  return _foodOntology;
}

function healthFoodOntologyUpdatedAt() {
  try {
    return statSync(HEALTH_FOOD_ONTOLOGY_PATH).mtime.toISOString();
  } catch {
    return null;
  }
}

function stableForSignature(value) {
  if (Array.isArray(value)) return value.map(stableForSignature);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.keys(value)
      .filter(key => key !== 'color')
      .sort()
      .map(key => [key, stableForSignature(value[key])])
  );
}

function hashSignature(value) {
  return createHash('sha256')
    .update(JSON.stringify(stableForSignature(value)))
    .digest('hex');
}

export function healthIntelSemanticUiConfig(ui = getUIConfig()) {
  return stableForSignature({
    conditionGroups: ui?.conditionGroups || [],
    rxGroups: ui?.rxGroups || [],
    bodyAreaMap: ui?.bodyAreaMap || {},
    rxMarkerMap: ui?.rxMarkerMap || {},
    definitions: ui?.definitions || {},
  });
}

function healthIntelInputSnapshot() {
  const latest = {
    dataPoints: latestTimestamp('health_data_points', 'created_at'),
    imports: latestTimestamp('health_ingestion_log', 'created_at', 'COALESCE(record_count, 0) > 0'),
    markers: latestTimestamp('health_markers', 'updated_at'),
    notes: latestTimestamp('health_notes', 'created_at'),
    curatedMedications: latestTimestamp('curated_medications', 'updated_at'),
    materialHealthContext: latestMaterialHealthTopicContextUpdatedAt(),
  };
  const latestInputAt = [
    ...Object.values(latest),
    healthFoodOntologyUpdatedAt(),
    HEALTH_INTEL_CONTEXT_UPDATED_AT,
  ].filter(Boolean).sort((a, b) => (dbDateMs(b) || 0) - (dbDateMs(a) || 0))[0] || null;

  return {
    version: 1,
    contextUpdatedAt: HEALTH_INTEL_CONTEXT_UPDATED_AT,
    latest,
    latestInputAt,
    healthUi: healthIntelSemanticUiConfig(),
    foodOntology: getFoodOntology() || null,
  };
}

export function healthIntelInputSignature(tab = 'all', snapshot = healthIntelInputSnapshot()) {
  return hashSignature({
    version: snapshot.version,
    tab,
    contextUpdatedAt: snapshot.contextUpdatedAt,
    latest: snapshot.latest,
    healthUi: snapshot.healthUi,
    foodOntology: snapshot.foodOntology,
  });
}

// ─── Cache API (prepared lazily so callers can import without a DB roundtrip) ─

let _stmts = null;
function stmts() {
  if (_stmts) return _stmts;
  _stmts = {
    getIntel: db.prepare(`
      SELECT tab, content, generated_at, model, input_tokens, output_tokens, input_signature
      FROM health_intel WHERE tab = ?
    `),
    upsertIntel: db.prepare(`
      INSERT INTO health_intel (tab, content, generated_at, model, input_tokens, output_tokens, input_signature)
      VALUES (?, ?, datetime('now'), ?, ?, ?, ?)
      ON CONFLICT(tab) DO UPDATE SET
        content = excluded.content,
        generated_at = excluded.generated_at,
        model = excluded.model,
        input_tokens = excluded.input_tokens,
        output_tokens = excluded.output_tokens,
        input_signature = excluded.input_signature
    `),
    listIntel: db.prepare(`
      SELECT tab, content, generated_at, model, input_tokens, output_tokens, input_signature
      FROM health_intel ORDER BY tab
    `),
    backfillInputSignature: db.prepare(`
      UPDATE health_intel
      SET input_signature = ?
      WHERE tab = ?
        AND COALESCE(input_signature, '') = ''
    `),
    // Health data — robotdojo schema
    allMarkers: db.prepare(`
      SELECT id, name, unit, group_id, ref_low, ref_high, target, trend, description, auto_created
      FROM health_markers ORDER BY group_id, name
    `),
    hasAnyDataPoint: db.prepare(`
      SELECT 1 AS n
      FROM health_data_points
      WHERE excluded = 0
      LIMIT 1
    `),
    activeMeds: db.prepare(`
      SELECT name, type, dose, frequency, timing, date_started, notes
      FROM curated_medications WHERE status = 'active'
      ORDER BY type, timing, name
    `),
    allMeds: db.prepare(`
      SELECT name, type, dose, frequency, timing, date_started, date_stopped, status, notes
      FROM curated_medications ORDER BY status, type, name
    `),
  };
  return _stmts;
}

function maybeBackfillIntelInputSignature(row, freshness) {
  if (!row || row.input_signature || freshness.stale || !freshness.current_input_signature) return row;
  try {
    stmts().backfillInputSignature.run(freshness.current_input_signature, row.tab);
    row.input_signature = freshness.current_input_signature;
  } catch (err) {
    console.warn('[health-intel] could not backfill input signature:', err.message);
  }
  return row;
}

export function getIntelContent(tab, { includeStale = false } = {}) {
  const row = stmts().getIntel.get(tab) || null;
  if (!row) return null;
  const content = normalizeIntelGeneratedContent(tab, row.content);
  const inputSnapshot = healthIntelInputSnapshot();
  const freshness = intelContentFreshnessReport(tab, content, {
    generatedAt: row.generated_at,
    outputTokens: row.output_tokens,
    inputSignature: row.input_signature,
    inputSnapshot,
  });
  const stale = freshness.stale;
  maybeBackfillIntelInputSignature(row, freshness);
  if (stale && !includeStale) return null;
  return { ...row, content, stale, freshness, stale_reasons: freshness.stale_reasons };
}

export function listIntel() {
  const inputSnapshot = healthIntelInputSnapshot();
  return stmts().listIntel.all().map(({ content, ...row }) => {
    const normalized = normalizeIntelGeneratedContent(row.tab, content);
    const freshness = intelContentFreshnessReport(row.tab, normalized, {
      generatedAt: row.generated_at,
      outputTokens: row.output_tokens,
      inputSignature: row.input_signature,
      inputSnapshot,
    });
    maybeBackfillIntelInputSignature(row, freshness);
    return {
      ...row,
      content_chars: String(normalized || '').length,
      stale: freshness.stale,
      stale_reasons: freshness.stale_reasons,
      latest_input_at: freshness.latest_input_at,
    };
  });
}

export function getIntelCacheStatus(tab) {
  const inputSnapshot = healthIntelInputSnapshot();
  const row = stmts().getIntel.get(tab) || null;
  if (!row) {
    const latestInputAt = latestHealthIntelInputUpdatedAt(inputSnapshot);
    return { tab, exists: false, stale: false, generated_at: null, model: null, latest_input_at: latestInputAt, stale_reasons: [] };
  }
  const content = normalizeIntelGeneratedContent(tab, row.content);
  const freshness = intelContentFreshnessReport(tab, content, {
    generatedAt: row.generated_at,
    outputTokens: row.output_tokens,
    inputSignature: row.input_signature,
    inputSnapshot,
  });
  maybeBackfillIntelInputSignature(row, freshness);
  return {
    tab: row.tab,
    exists: true,
    stale: freshness.stale,
    stale_reasons: freshness.stale_reasons,
    missing_requirements: freshness.missing_requirements,
    latest_input_at: freshness.latest_input_at,
    current_input_signature: freshness.current_input_signature,
    input_signature: row.input_signature || '',
    input_stale: freshness.input_stale,
    signature_stale: freshness.signature_stale,
    generated_at: row.generated_at,
    model: row.model,
    input_tokens: row.input_tokens,
    output_tokens: row.output_tokens,
    content_chars: String(content || '').length,
  };
}

function saveIntelContent(tab, content, model, usage) {
  stmts().upsertIntel.run(
    tab, content, model,
    usage?.input_tokens || 0,
    usage?.output_tokens || 0,
    healthIntelInputSignature(tab),
  );
}

function maxOutputTokensForTab(tab) {
  return MAX_OUTPUT_TOKENS[tab] || 2000;
}

const REQUIRED_TAB_SECTIONS = {
  insights: [
    /##\s+Current State\b/,
    /##\s+Risk\b/,
    /##\s+Diet\b/,
    /##\s+Rx\b/,
    /##\s+Next Visit\b/,
    /##\s+Watch\b/,
  ],
  intel: [
    /##\s+Current State\b/,
    /##\s+Active Risk Map\b/,
    /##\s+Intervention Read\b/,
    /##\s+Watchlist\b/,
    /##\s+Next Data Needed\b/,
  ],
  diet: [
    /##\s+Strategy\b/,
    /##\s+Tier 1:\s+Daily Staples\b/,
    /##\s+Tier 2:\s+Weekly Rotation\b/,
    /##\s+Tier 3:\s+Allowable Exceptions\b/,
    /##\s+Tier 4:\s+Danger Zone\b/,
    /##\s+Chef'?s Narrative\b/,
    /##\s+Current Adjustments\b/,
  ],
  rx: [
    /##\s+Current Regimen\b/,
    /##\s+Mechanism Map\b/,
    /##\s+Monitoring\b/,
    /##\s+Interaction \/ Contraindication Watch\b/,
    /##\s+Protocol Gaps\b/,
    /##\s+Clinician Questions\b/,
  ],
  nextvisit: [
    /##\s+Decision Agenda\b/,
    /##\s+Tests To Consider\b/,
    /##\s+Discussion Topics\b/,
    /##\s+Questions To Ask\b/,
    /##\s+Bring\b/,
  ],
  chronology: [
    /##\s+User-Reported History\b/,
    /##\s+Family History\b/,
    /##\s+Material Health Events\b/,
  ],
};

const REQUIRED_TAB_FACTS = {
  insights: [
    /APOE4|APOE\s*e3\/e4|ApoB|LDL|lipid/i,
    /Humira|Adalimumab|Olumiant|Baricitinib|Rosuvastatin/i,
  ],
  intel: [
    /APOE4|APOE\s*e3\/e4|lipid|cardiovascular/i,
    /ApoB|LDL|non[-\s]?HDL/i,
    /Humira|Adalimumab|Olumiant|Baricitinib|immune|autoimmune|inflammation/i,
    /kidney\s+stone|hypercalciuria|urine\s+calcium|Chlorthalidone|calcium/i,
    /ALT|AST|liver|bilirubin|Gilbert/i,
  ],
  diet: [
    /tier\s+1\s+fat/i,
    /raw\s+spinach/i,
    /almond[-\s]flour/i,
    /citrus\s+squeeze/i,
    /clothe\s+the\s+carbs/i,
    /APOE4|lipid|cardiovascular/i,
    /kidney\s+stone|stone\s+risk|calcium/i,
    /inflammation|inflammatory/i,
  ],
  rx: [
    /Humira|Adalimumab/i,
    /Olumiant|Baricitinib/i,
    /Rosuvastatin/i,
    /Ezetimibe/i,
    /Chlorthalidone/i,
    /Finasteride/i,
    /held|on[-_\s]?hold|not\s+active|stopped|discontinued/i,
    /ALT|AST|liver/i,
    /CBC|ANC|lymph|platelet|hemoglobin|immune/i,
    /calcium|urine\s+calcium|stone/i,
  ],
  nextvisit: [
    /D3\/K2|VDR|VDBP|calcitriol|25[-\s]?OH[-\s]?D|vitamin\s+D/i,
    /Chlorthalidone|urine\s+calcium|hypercalciuria|kidney\s+stone/i,
    /ALT|AST|Olumiant|Baricitinib|liver/i,
    /DFI|TTC|Finasteride/i,
    /ApoB|LDL|non[-\s]?HDL|APOE4|lipid/i,
  ],
  chronology: [
    /MedicationRequest|prescription|actual\s+use/i,
    /Chlorthalidone|HCTZ/i,
    /VDR|VDBP|hypercalciuria|kidney\s+stone|calcium/i,
    /DFI|TTC|Finasteride|Olumiant|Humira/i,
  ],
};

const FORBIDDEN_TAB_PATTERNS = {
  chronology: [
    /^###\s+/m,
    /^##\s+\d{4}\b/m,
    /^##\s+(?!User-Reported History\b|Family History\b|Material Health Events\b)/m,
  ],
};

function latestTimestamp(table, column, where = '') {
  if (!hasTable(table)) return null;
  try {
    const sql = `SELECT MAX(${column}) AS value FROM ${table}${where ? ` WHERE ${where}` : ''}`;
    return db.prepare(sql).get()?.value || null;
  } catch {
    return null;
  }
}

function latestMaterialHealthTopicContextUpdatedAt() {
  if (!hasTable('topic_context_history')) return null;
  try {
    return db.prepare(`
      SELECT MAX(created_at) AS value
      FROM topic_context_history
      WHERE topic_slug = 'health'
        AND COALESCE(source, '') != 'synthesis'
    `).get()?.value || null;
  } catch {
    return null;
  }
}

function dbDateMs(value) {
  if (!value) return null;
  const text = String(value).trim();
  if (!text) return null;
  const normalized = /\dT\d/.test(text) ? text : `${text.replace(' ', 'T')}Z`;
  const ms = Date.parse(normalized);
  return Number.isFinite(ms) ? ms : null;
}

export function latestHealthIntelInputUpdatedAt(inputSnapshot = null) {
  // Display config mtimes are intentionally excluded. Semantic ontology changes
  // are handled by healthIntelInputSignature(); palette edits must not trigger
  // an expensive clinical synthesis pass.
  return (inputSnapshot || healthIntelInputSnapshot()).latestInputAt;
}

function intelGeneratedBeforeLatestHealthInput(generatedAt) {
  const generatedMs = dbDateMs(generatedAt);
  if (!generatedMs) return false;
  const latestMs = dbDateMs(latestHealthIntelInputUpdatedAt());
  if (!latestMs) return false;
  return generatedMs < latestMs;
}

export function missingIntelContentRequirements(tab, content) {
  const required = REQUIRED_TAB_SECTIONS[tab];
  const requiredFacts = REQUIRED_TAB_FACTS[tab] || [];
  const forbidden = FORBIDDEN_TAB_PATTERNS[tab] || [];
  if (!required) return [];
  const value = String(content || '');
  return [
    ...required
      .filter(pattern => !pattern.test(value))
      .map(pattern => `missing required section ${pattern}`),
    ...requiredFacts
      .filter(pattern => !pattern.test(value))
      .map(pattern => `missing required fact ${pattern}`),
    ...forbidden
      .filter(pattern => pattern.test(value))
      .map(pattern => `forbidden tab pattern ${pattern}`),
  ];
}

function intelOutputCompletenessIssues(tab, content, { outputTokens = null } = {}) {
  const value = String(content || '').trim();
  const issues = [];
  const used = Number(outputTokens || 0);
  const max = maxOutputTokensForTab(tab);
  if (Number.isFinite(used) && used > 0 && used >= max - 8) {
    issues.push(`generated output reached the ${tab} token ceiling (${used}/${max}); regenerate with the expanded budget`);
  }
  if (value && used >= max - 8) {
    const tail = value.slice(-120);
    if (!/[.!?)}\]"'`]\s*$/.test(tail)) {
      issues.push('generated output appears clipped before a complete final sentence');
    }
  }
  return issues;
}

export function intelContentFreshnessReport(
  tab,
  content,
  { generatedAt = null, outputTokens = null, inputSignature = '', inputSnapshot = null } = {}
) {
  const snapshot = inputSnapshot || healthIntelInputSnapshot();
  const missing = missingIntelContentRequirements(tab, content);
  const outputIssues = intelOutputCompletenessIssues(tab, content, { outputTokens });
  const latestInputAt = latestHealthIntelInputUpdatedAt(snapshot);
  const generatedMs = dbDateMs(generatedAt);
  const latestMs = dbDateMs(latestInputAt);
  const inputStale = Boolean(generatedMs && latestMs && generatedMs < latestMs);
  const currentInputSignature = healthIntelInputSignature(tab, snapshot);
  const signatureStale = Boolean(inputSignature && currentInputSignature && inputSignature !== currentInputSignature);
  const staleReasons = [];
  if (missing.length) staleReasons.push(`Tab contract changed or generated content is incomplete (${missing.length} issue${missing.length === 1 ? '' : 's'}).`);
  staleReasons.push(...outputIssues);
  if (inputStale) staleReasons.push(`Generated before latest health intel input or contract update (${latestInputAt}).`);
  if (signatureStale) staleReasons.push('Generated before material health intelligence inputs changed.');
  return {
    stale: staleReasons.length > 0,
    stale_reasons: staleReasons,
    missing_requirements: [...missing, ...outputIssues],
    generated_at: generatedAt || null,
    latest_input_at: latestInputAt,
    input_signature: inputSignature || '',
    current_input_signature: currentInputSignature,
    input_stale: inputStale,
    signature_stale: signatureStale,
  };
}

export function isIntelContentStale(tab, content, { generatedAt = null, outputTokens = null } = {}) {
  return intelContentFreshnessReport(tab, content, { generatedAt, outputTokens }).stale;
}

export function normalizeIntelGeneratedContent(tab, content) {
  const value = String(content || '').trim();
  if (tab !== 'chronology') return value;
  const allowedSections = new Set(['User-Reported History', 'Family History', 'Material Health Events']);
  let keep = false;
  return value
    .split('\n')
    .filter(line => {
      const trimmed = line.trim();
      if (/^###\s+/.test(trimmed)) return false;
      const h2 = trimmed.match(/^##\s+(.+)$/);
      if (h2) {
        const section = h2[1].trim();
        keep = allowedSections.has(section);
        return keep;
      }
      return keep;
    })
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

// ─── Health context builder ───────────────────────────────────────────────

function hasTable(tableName) {
  try {
    return !!db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(tableName);
  } catch {
    return false;
  }
}

function hasColumn(tableName, columnName) {
  try {
    return db.prepare(`PRAGMA table_info(${tableName})`).all().some(row => row.name === columnName);
  } catch {
    return false;
  }
}

function scalar(sql, key = 'n') {
  try {
    return db.prepare(sql).get()?.[key] ?? null;
  } catch {
    return null;
  }
}

function capSection(text, maxChars, label) {
  const value = String(text || '');
  if (!maxChars || value.length <= maxChars) return value;
  return `${value.slice(0, maxChars).trim()}\n\n[${label} truncated to fit the generation budget. Use only facts shown above.]`;
}

function markerCanonicalIdMap() {
  const ids = new Map();
  for (const marker of stmts().allMarkers.all()) {
    const enriched = enrichHealthMarker(marker);
    ids.set(marker.id, enriched.canonicalId || marker.id);
  }
  return ids;
}

function markerDataSummaryByMarker({ sources = null, markerFilter = null } = {}) {
  const canonicalIds = markerCanonicalIdMap();
  const markersById = new Map(allIntelMarkers().map(marker => [marker.id, marker]));
  const pointsByMarker = new Map();
  const sourceSet = sources ? new Set(sources) : null;
  for (const [markerId, rows] of listDataPointsGroupedByMarker(db).entries()) {
    const canonicalId = canonicalIds.get(markerId) || markerId;
    const marker = markersById.get(canonicalId) || null;
    const list = pointsByMarker.get(canonicalId) || [];
    list.push(...rows
      .map(intelDataPointFromRow)
      .map(point => normalizeIntelDataPoint(marker, point))
      .filter(point => point.date && Number.isFinite(point.value))
      .filter(point => !point.hiddenReason)
      .filter(point => !sourceSet || sourceSet.has(point.source)));
    pointsByMarker.set(canonicalId, list);
  }

  const byMarker = new Map();
  for (const [markerId, points] of pointsByMarker.entries()) {
    const marker = markersById.get(markerId) || null;
    if (markerFilter && !markerFilter(marker, points)) continue;
    const data = collapseIntelDuplicateDataPoints(points)
      .sort((a, b) => String(a.date || '').localeCompare(String(b.date || '')));
    if (!data.length) continue;
    const first = data[0];
    const latest = data[data.length - 1];
    byMarker.set(markerId, {
      marker_id: markerId,
      first_date: first.date,
      first_value: first.value,
      latest_date: latest.date,
      latest_value: latest.value,
      data_count: data.length,
      latest_source: latest.source || '',
      sources: [...new Set(data.map(point => point.source).filter(Boolean))],
    });
  }
  return byMarker;
}

const INTEL_SOURCE_PRIORITY = {
  'pdf-lab': 0,
  fhir: 1,
  'derived-lipid': 1.5,
  'apple-health': 2,
  'oura-json': 3,
  oura_sync: 3,
  eight_sleep_sync: 3,
  'wearable-summary': 4,
};
const INTEL_LAB_BACKED_SOURCES = new Set(['pdf-lab', 'fhir', 'manual', 'derived-lipid']);
const INTEL_WEARABLE_CONTEXT_SOURCES = new Set(['apple-health', 'oura-json', 'oura_sync', 'eight_sleep_sync', 'wearable-summary']);
const INTEL_NON_LAB_CONTEXT_GROUPS = new Set(['body_composition', 'sleep', 'user_tracked', 'vitals']);
const INTEL_ABSOLUTE_CELL_MARKERS = new Set(['anc', 'lymph_abs', 'eos_absolute', 'monocytes_absolute', 'baso_absolute']);
const INTEL_KNOWN_2020_24HR_URINE_TABLE_SHIFT_REASON = 'known 2020 24-hour urine table extraction mismatch';
const INTEL_KNOWN_2020_24HR_URINE_TABLE_SHIFT_MARKERS = new Set([
  'ca_24_kg',
  'protein_catabolic_rate',
  'ss_cap',
  'urine_ammonium',
  'urine_ph',
  'urine_phosphorus',
  'urine_urea_nitrogen',
]);

function intelQualityMarkerId(marker) {
  return marker?.canonicalId || marker?.id || '';
}

function intelRefHigh(marker) {
  return Number(marker?.ref_high ?? marker?.refRange?.high);
}

function intelRefLow(marker) {
  return Number(marker?.ref_low ?? marker?.refRange?.low);
}

function intelHasCellCountUnit(unit) {
  return /cells\/?u?l/i.test(unit || '');
}

function intelHasThousandCellUnit(unit) {
  return /(?:x10e3|10\*3|10\^3|k)\/?u?l/i.test(unit || '');
}

function intelHasAbsoluteCellCountScale(marker) {
  const id = intelQualityMarkerId(marker);
  const high = intelRefHigh(marker);
  if (Number.isFinite(high) && high >= 300 && intelHasCellCountUnit(marker?.unit)) return true;
  return INTEL_ABSOLUTE_CELL_MARKERS.has(id) && (intelHasCellCountUnit(marker?.unit) || intelHasThousandCellUnit(marker?.unit));
}

function intelKnownBad2020UrineExtraction(marker, point) {
  const id = intelQualityMarkerId(marker);
  if (!INTEL_KNOWN_2020_24HR_URINE_TABLE_SHIFT_MARKERS.has(id)) return false;
  return /Master_Medical_Vault_Data_Lab_Work_2020_e029dd30/i.test(point?.sourceFile || point?.source_file || '');
}

function genericIntelPointHiddenReason(marker, point, value) {
  const id = intelQualityMarkerId(marker);
  if (!Number.isFinite(value)) return 'non-numeric';
  if (intelKnownBad2020UrineExtraction(marker, point)) return INTEL_KNOWN_2020_24HR_URINE_TABLE_SHIFT_REASON;
  if (id === 'creatinine' && value > 5) return 'serum creatinine unit mismatch';
  if (id === 'body_fat' && value > 45) return 'body-fat import outlier';
  if ((id === 'oura_rhr' || id === 'eight_sleep_rhr') && value > 110) return 'resting-heart-rate outlier';
  if ((id === 'oura_total_sleep' || id === 'eight_sleep_total_sleep') && (value < 2 || value > 13.5)) return 'partial or over-merged sleep day';
  if ((id === 'oura_deep_sleep' || id === 'oura_rem_sleep' || id === 'eight_sleep_deep_sleep' || id === 'eight_sleep_rem_sleep') && (value < 5 || value > 360)) return 'partial or over-merged sleep-stage day';
  if (value === 0 && Number.isFinite(intelRefLow(marker)) && intelRefLow(marker) > 0 && marker?.direction !== 'lower') {
    return 'zero placeholder below physiologic range';
  }
  return '';
}

function intelSourcePriority(point) {
  return INTEL_SOURCE_PRIORITY[point?.source] ?? 9;
}

function intelDataPointFromRow(row) {
  return {
    date: String(row.date || ''),
    value: Number(row.value),
    source: row.source || '',
    sourceFile: row.source_file || '',
    sourceId: row.source_id || '',
    specimenType: row.specimen_type || 'unknown',
  };
}

function normalizeIntelDataPoint(marker, point) {
  if (!point) return point;
  const value = Number(point.value);
  if (!Number.isFinite(value)) return point;
  const id = intelQualityMarkerId(marker);
  if (intelHasAbsoluteCellCountScale(marker) && value > 0) {
    if (value >= 10 && value <= 100) {
      return {
        ...point,
        hiddenReason: 'percent value mapped into absolute count chart',
      };
    }
    if (value < 10) {
      return {
        ...point,
        value: Number((value * 1000).toFixed(1)),
        rawValue: value,
        qualityNote: 'converted x10E3/uL to cells/uL',
      };
    }
  }
  if (id === 'height' && /in/i.test(marker?.unit || '') && value > 100 && value < 250) {
    return {
      ...point,
      value: Number((value / 2.54).toFixed(1)),
      rawValue: value,
      qualityNote: 'converted cm to in',
    };
  }
  if (id === 'weight' && /lb/i.test(marker?.unit || '') && value >= 40 && value <= 120) {
    return {
      ...point,
      value: Number((value * 2.2046226218).toFixed(1)),
      rawValue: value,
      qualityNote: 'converted kg to lb',
    };
  }
  const hiddenReason = genericIntelPointHiddenReason(marker, point, value);
  if (hiddenReason) return { ...point, hiddenReason };
  return point;
}

function intelDuplicateKey(point) {
  const value = Number(point?.value);
  if (!Number.isFinite(value)) return null;
  return `${point.date || ''}|${value.toPrecision(12)}`;
}

function representativeIntelDuplicatePoint(points) {
  return [...points].sort((a, b) => {
    const priority = intelSourcePriority(a) - intelSourcePriority(b);
    if (priority) return priority;
    return String(a.sourceFile || '').localeCompare(String(b.sourceFile || ''));
  })[0];
}

function collapseIntelDuplicateDataPoints(points) {
  if (!Array.isArray(points) || points.length < 2) return points || [];
  const buckets = new Map();
  const passthrough = [];
  for (const point of points) {
    const key = intelDuplicateKey(point);
    if (!key) {
      passthrough.push(point);
      continue;
    }
    const list = buckets.get(key);
    if (list) list.push(point);
    else buckets.set(key, [point]);
  }
  const out = [...passthrough];
  for (const group of buckets.values()) out.push(group.length > 1 ? representativeIntelDuplicatePoint(group) : group[0]);
  return out;
}

function canonicalIntelRepresentative(list, canonicalId) {
  const exact = list.find(marker => marker.id === canonicalId);
  if (exact) return exact;
  return [...list].sort((a, b) => {
    const aImported = a.group_id === 'auto_imported' || a.auto_created ? 1 : 0;
    const bImported = b.group_id === 'auto_imported' || b.auto_created ? 1 : 0;
    if (aImported !== bImported) return aImported - bImported;
    return String(a.name || '').localeCompare(String(b.name || ''));
  })[0];
}

function allIntelMarkers() {
  const grouped = new Map();
  for (const marker of stmts().allMarkers.all().map(marker => enrichHealthMarker(marker))) {
    const key = marker.canonicalId || marker.id;
    const list = grouped.get(key);
    if (list) list.push(marker);
    else grouped.set(key, [marker]);
  }

  const merged = [];
  for (const [canonicalId, list] of grouped.entries()) {
    const primary = canonicalIntelRepresentative(list, canonicalId);
    merged.push({
      ...primary,
      id: canonicalId,
      canonicalId,
      aliases: [...new Set(list.map(marker => marker.id).filter(id => id && id !== canonicalId))],
      auto_created: Boolean(primary.auto_created),
    });
  }

  return merged.sort((a, b) => {
    const group = String(healthMarkerGroupLabel(a.group_id)).localeCompare(String(healthMarkerGroupLabel(b.group_id)));
    if (group) return group;
    return String(a.name || '').localeCompare(String(b.name || ''));
  });
}

function latestVisibleIntelPointForMarkerId(markerId, {
  canonicalIds = markerCanonicalIdMap(),
  markersById = new Map(allIntelMarkers().map(marker => [marker.id, marker])),
  dataByRawMarker = listDataPointsGroupedByMarker(db),
} = {}) {
  const canonicalId = canonicalIds.get(markerId) || markerId;
  const marker = markersById.get(canonicalId) || null;
  const rows = dataByRawMarker.get(markerId) || [];
  const points = collapseIntelDuplicateDataPoints(rows
    .map(intelDataPointFromRow)
    .map(point => normalizeIntelDataPoint(marker, point))
    .filter(point => point.date && Number.isFinite(point.value))
    .filter(point => !point.hiddenReason))
    .sort((a, b) => String(a.date || '').localeCompare(String(b.date || '')));
  const point = points[points.length - 1] || null;
  return { marker, point };
}

function buildComputedIntelQualityFilterContext({ limit = 12 } = {}) {
  const canonicalIds = markerCanonicalIdMap();
  const markersById = new Map(allIntelMarkers().map(marker => [marker.id, marker]));
  const dataByRawMarker = listDataPointsGroupedByMarker(db);
  const hiddenReasons = new Map();
  const conversionNotes = new Map();
  const examples = [];

  for (const [markerId, rows] of dataByRawMarker.entries()) {
    const canonicalId = canonicalIds.get(markerId) || markerId;
    const marker = markersById.get(canonicalId) || null;
    for (const row of rows) {
      const point = normalizeIntelDataPoint(marker, intelDataPointFromRow(row));
      if (point?.hiddenReason) {
        hiddenReasons.set(point.hiddenReason, (hiddenReasons.get(point.hiddenReason) || 0) + 1);
        if (examples.length < limit) {
          const label = marker?.name || markerId;
          const source = point.sourceId ? ` (${point.sourceId})` : '';
          examples.push(`- ${label} on ${point.date || 'unknown date'}: ${point.hiddenReason}${source}`);
        }
      }
      if (point?.qualityNote && !point.hiddenReason) {
        conversionNotes.set(point.qualityNote, (conversionNotes.get(point.qualityNote) || 0) + 1);
      }
    }
  }

  if (!hiddenReasons.size && !conversionNotes.size) return '';
  const lines = [
    '### Computed Chart-Grade Quality Filters',
    '',
    'These filters are applied before charting and synthesis. Hidden rows are import artifacts, not patient facts.',
  ];
  if (hiddenReasons.size) {
    lines.push('', 'Hidden before synthesis:');
    for (const [reason, count] of [...hiddenReasons.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))) {
      lines.push(`- ${count} row${count === 1 ? '' : 's'}: ${reason}`);
    }
  }
  if (conversionNotes.size) {
    lines.push('', 'Normalized before synthesis:');
    for (const [note, count] of [...conversionNotes.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))) {
      lines.push(`- ${count} row${count === 1 ? '' : 's'}: ${note}`);
    }
  }
  if (examples.length) {
    lines.push('', 'Hidden-row examples for review:');
    lines.push(...examples);
  }
  return lines.join('\n');
}

function markerSnapshot(marker, summary) {
  if (!summary) return null;

  const latest = {
    date: summary.latest_date,
    value: summary.latest_value,
  };
  const first = {
    date: summary.first_date,
    value: summary.first_value,
  };
  const dataCount = Number(summary.data_count || 0);
  if (!latest.date || dataCount <= 0) return null;

  let flag = '';
  if (marker.ref_low != null && latest.value < marker.ref_low) flag = 'LOW';
  if (marker.ref_high != null && latest.value > marker.ref_high) flag = 'HIGH';

  let pct = null;
  let trend = '';
  if (dataCount > 1) {
    if (first.value !== 0) {
      pct = ((latest.value - first.value) / first.value) * 100;
      const sign = pct > 0 ? '+' : '';
      trend = ` | ${sign}${pct.toFixed(1)}% over ${dataCount} readings (${first.date} -> ${latest.date})`;
    }
  }

  const ref = [
    marker.ref_low != null ? `low ${marker.ref_low}` : null,
    marker.ref_high != null ? `high ${marker.ref_high}` : null,
    marker.target != null ? `target ${marker.target}` : null,
  ].filter(Boolean).join(', ');

  return {
    marker,
    latest,
    dataCount,
    hasFlag: Boolean(flag),
    absPct: pct == null ? 0 : Math.abs(pct),
    line: `- **${marker.name}** [${healthMarkerGroupLabel(marker.group_id)}]: ${latest.value} ${marker.unit || ''} (${latest.date})${ref ? ` | ref ${ref}` : ''}${flag ? ` | ${flag}` : ''}${trend}`,
  };
}

const HEALTH_GROUP_LABELS = {
  labs: 'Lab Results',
  auto_imported: 'Lab Results',
  vitals: 'Vitals',
  body_composition: 'Body Composition',
  metabolic: 'Metabolic',
  cardiovascular: 'Cardiovascular',
  blood: 'Blood Counts',
  kidney: 'Kidney',
  liver: 'Liver',
  hormones: 'Hormones',
  inflammation: 'Inflammation',
  vitamins_minerals: 'Vitamins & Minerals',
  sleep: 'Sleep & Recovery',
  user_tracked: 'User Tracked',
};

function healthMarkerGroupLabel(groupId) {
  const id = String(groupId || '').trim();
  return HEALTH_GROUP_LABELS[id] || id || 'unknown';
}

function healthMarkerReviewContext(row) {
  const label = healthMarkerGroupLabel(row?.group_id);
  if (row?.auto_created || row?.group_id === 'auto_imported') {
    return `${label}; auto-created import label, needs ontology review`;
  }
  return label;
}

function compareSnapshots(a, b) {
  if (a.hasFlag !== b.hasFlag) return a.hasFlag ? -1 : 1;
  if (b.absPct !== a.absPct) return b.absPct - a.absPct;
  if (b.dataCount !== a.dataCount) return b.dataCount - a.dataCount;
  return String(a.marker.name).localeCompare(String(b.marker.name));
}

function buildMarkerTrends({ limit = 140 } = {}) {
  const markers = allIntelMarkers();
  if (!markers.length) return '';

  const lines = ['## All Marker Trends', ''];
  const dataByMarker = markerDataSummaryByMarker();
  const snapshots = markers.map(marker => markerSnapshot(marker, dataByMarker.get(marker.id))).filter(Boolean).sort(compareSnapshots);
  const shown = snapshots.slice(0, limit);
  if (snapshots.length > shown.length) {
    lines.push(`Prioritized ${shown.length} of ${snapshots.length} markers by out-of-range status, trend magnitude, and data density. Do not infer facts from omitted markers.`);
    lines.push('');
  }
  for (const snap of shown) lines.push(snap.line);
  return lines.join('\n');
}

function buildLatestLabsSummary({ limit = 160 } = {}) {
  const markers = allIntelMarkers();
  const lines = ['### Latest Lab Results Summary', ''];
  const dataByMarker = markerDataSummaryByMarker({
    sources: INTEL_LAB_BACKED_SOURCES,
    markerFilter: marker => marker && !INTEL_NON_LAB_CONTEXT_GROUPS.has(marker.group_id),
  });
  const snapshots = markers.map(marker => markerSnapshot(marker, dataByMarker.get(marker.id))).filter(Boolean).sort(compareSnapshots);
  const shown = snapshots.slice(0, limit);
  if (snapshots.length > shown.length) {
    lines.push(`Prioritized ${shown.length} of ${snapshots.length} latest marker values. Do not infer facts from omitted markers.`);
    lines.push('');
  }
  for (const snap of shown) {
    const flag = snap.hasFlag ? ' | out of range' : '';
    lines.push(`- **${snap.marker.name}**: ${snap.latest.value} ${snap.marker.unit || ''} (${snap.latest.date})${flag}`);
  }
  return shown.length ? lines.join('\n') : '';
}

function nonLabContextMarker(marker, points) {
  if (!marker || !points?.length) return false;
  if (INTEL_NON_LAB_CONTEXT_GROUPS.has(marker.group_id)) return true;
  return points.some(point => INTEL_WEARABLE_CONTEXT_SOURCES.has(point.source));
}

function buildNonLabSignalsSummary({ limit = 50 } = {}) {
  const markers = allIntelMarkers();
  const lines = [
    '### Non-Lab Clinical, Wearable, And User-Tracked Signals',
    '',
    'These values come from Apple Health, Oura, user-tracked, vitals, sleep, or body-composition imports. Use them as recovery/context signals, not as lab results.',
    '',
  ];
  const dataByMarker = markerDataSummaryByMarker({ markerFilter: nonLabContextMarker });
  const snapshots = markers.map(marker => markerSnapshot(marker, dataByMarker.get(marker.id))).filter(Boolean).sort(compareSnapshots);
  const shown = snapshots.slice(0, limit);
  if (snapshots.length > shown.length) {
    lines.push(`Prioritized ${shown.length} of ${snapshots.length} non-lab signals by trend magnitude and data density. Do not infer facts from omitted signals.`);
    lines.push('');
  }
  for (const snap of shown) lines.push(snap.line);
  return shown.length ? lines.join('\n') : '';
}

function medStatusLabel(status) {
  const normalized = String(status || '').toLowerCase();
  if (normalized === 'on_hold') return 'on hold';
  if (normalized === 'held') return 'held';
  if (normalized === 'stopped') return 'stopped';
  if (normalized === 'discontinued') return 'discontinued';
  if (normalized === 'active') return 'active';
  return normalized || 'unknown';
}

function medLine(m, { includeStatus = false } = {}) {
  const details = [m.dose, m.frequency, m.timing].filter(Boolean).join(' | ');
  const status = includeStatus ? ` (${medStatusLabel(m.status)})` : '';
  return `- **${m.name}**${details ? ` — ${details}` : ''}${status}`;
}

function buildActiveMeds() {
  const meds = listEffectiveMedicationsRaw(db);
  if (!meds.length) return '';

  const active = meds.filter(m => m.status === 'active');
  const inactive = meds.filter(m => m.status !== 'active');
  const rx = active.filter(m => m.type === 'rx');
  const supps = active.filter(m => m.type === 'supplement');
  const heldRx = inactive.filter(m => m.type === 'rx');
  const heldSupps = inactive.filter(m => m.type === 'supplement');
  const lines = ['### Current Medications & Supplements', ''];
  lines.push('**Authority:** This structured medication ledger is the current-use source of truth. Older timelines and imported MedicationRequest records describe prescriptions or prior decisions and must not override these statuses unless explicitly newer.');
  lines.push('');

  if (rx.length) {
    lines.push('**Active prescriptions:**');
    for (const m of rx) {
      lines.push(medLine(m));
      if (m.notes) lines.push(`  _${m.notes}_`);
    }
    lines.push('');
  }

  if (supps.length) {
    lines.push('**Active supplements:**');
    for (const m of supps) {
      lines.push(medLine(m));
      if (m.notes) lines.push(`  _${m.notes}_`);
    }
    lines.push('');
  }

  if (heldRx.length) {
    lines.push('**Held / on-hold prescriptions:**');
    for (const m of heldRx) {
      lines.push(medLine(m, { includeStatus: true }));
      if (m.date_stopped) lines.push(`  _Stopped/held date: ${m.date_stopped}._`);
      if (m.notes) lines.push(`  _${m.notes}_`);
    }
    lines.push('');
  }

  if (heldSupps.length) {
    lines.push('**Held / planned supplements:**');
    for (const m of heldSupps) {
      lines.push(medLine(m, { includeStatus: true }));
      if (m.notes) lines.push(`  _${m.notes}_`);
    }
  }

  return lines.join('\n').trim();
}

function formatFoodOntology() {
  const ontology = getFoodOntology();
  if (!ontology) return '';

  const lines = [
    `## Health Food Ontology - ${ontology.title || 'Personal Food Guide'}`,
    '',
  ];
  if (ontology.strategy) {
    lines.push('### Strategy');
    lines.push(ontology.strategy);
    lines.push('');
  }
  if (Array.isArray(ontology.patientDrivers) && ontology.patientDrivers.length) {
    lines.push('### Patient Drivers');
    for (const driver of ontology.patientDrivers) lines.push(`- ${driver}`);
    lines.push('');
  }
  if (Array.isArray(ontology.tiers)) {
    for (const tier of ontology.tiers) {
      lines.push(`### Tier ${tier.level}: ${tier.name} (${tier.frequency})`);
      if (tier.subtitle) lines.push(tier.subtitle);
      for (const [category, foods] of Object.entries(tier.categories || {})) {
        const items = Array.isArray(foods) ? foods.join('; ') : String(foods || '');
        lines.push(`- ${category}: ${items}`);
      }
      lines.push('');
    }
  }
  if (Array.isArray(ontology.chefNarrative) && ontology.chefNarrative.length) {
    lines.push("### Chef's Narrative");
    for (const rule of ontology.chefNarrative) {
      lines.push(`- ${rule.name}: ${rule.rule}`);
    }
    lines.push('');
  }
  lines.push('### Non-negotiable Interpretation');
  lines.push('- This is patient-specific guidance recovered from the health history, not generic diet advice.');
  lines.push('- Preserve the four-tier structure and frequencies unless later context explicitly changes a food item.');
  lines.push('- Tie any adjustment to provided labs, diagnoses, medications, symptoms, or workbench decisions.');
  return lines.join('\n');
}

function safeJsonSummary(value) {
  if (!value) return '';
  try {
    const parsed = JSON.parse(value);
    if (parsed?.title) return String(parsed.title);
    if (parsed?.summary) return String(parsed.summary);
    if (parsed?.content_excerpt) return String(parsed.content_excerpt);
  } catch { /* metadata is optional */ }
  return '';
}

function valueStatus(row) {
  const value = Number(row.value);
  if (!Number.isFinite(value)) return 'unknown';
  if (row.ref_low != null && value < Number(row.ref_low)) return 'LOW';
  if (row.ref_high != null && value > Number(row.ref_high)) return 'HIGH';
  return 'in range';
}

function buildYearlyHealthCoverage() {
  if (!hasTable('health_data_points')) return '';
  const rows = db.prepare(`
    SELECT substr(date, 1, 4) AS year, COUNT(*) AS count, MIN(date) AS first_date, MAX(date) AS last_date
    FROM health_data_points
    WHERE excluded = 0
    GROUP BY year
    ORDER BY year ASC
  `).all();
  if (!rows.length) return '';
  const lines = ['### Whole Available Health Data Coverage', '', '| Year | Data points | Range |', '| --- | ---: | --- |'];
  for (const row of rows) {
    lines.push(`| ${row.year} | ${row.count} | ${row.first_date} to ${row.last_date} |`);
  }
  return lines.join('\n');
}

function buildHealthDataQualityContext({ autoLimit = 30, stagedLimit = 16 } = {}) {
  if (!hasTable('health_data_points')) return '';
  const lines = [
    '## Health Data Quality And Import Coverage',
    '',
    'Use this section to distinguish source-backed values from review-needed imported labels. Auto-created markers are real extracted values, but their marker name/category may need curation before being treated as durable ontology.',
  ];

  const coverage = db.prepare(`
    SELECT
      source,
      COUNT(*) AS points,
      COUNT(DISTINCT marker_id) AS markers,
      COUNT(DISTINCT NULLIF(source_file, '')) AS files,
      MIN(date) AS first_date,
      MAX(date) AS last_date
    FROM health_data_points
    WHERE excluded = 0
    GROUP BY source
    ORDER BY points DESC, source ASC
  `).all();
  if (coverage.length) {
    lines.push('', '### Imported Source Coverage', '', '| Source | Points | Markers | Files | Date span |', '| --- | ---: | ---: | ---: | --- |');
    for (const row of coverage) {
      const span = [row.first_date, row.last_date].filter(Boolean).join(' to ') || 'not available';
      lines.push(`| ${row.source || 'unknown'} | ${row.points} | ${row.markers} | ${row.files || 0} | ${span} |`);
    }
  }

  const emptySourceIds = scalar("SELECT COUNT(*) AS n FROM health_data_points WHERE source_id IS NULL OR source_id = ''");
  const legacyPdfPoints = scalar("SELECT COUNT(*) AS n FROM health_data_points WHERE source = 'pdf'");
  const excludedPoints = scalar('SELECT COUNT(*) AS n FROM health_data_points WHERE excluded = 1');
  const activePoints = scalar('SELECT COUNT(*) AS n FROM health_data_points WHERE excluded = 0');
  const warnings = [];
  if (emptySourceIds) warnings.push(`${emptySourceIds} rows are missing source_id and may deduplicate poorly.`);
  if (legacyPdfPoints) warnings.push(`${legacyPdfPoints} legacy pdf rows remain and may need migration to pdf-lab.`);
  if (excludedPoints) warnings.push(`${excludedPoints} rows are excluded from charts/synthesis due to import quality review.`);
  if (activePoints != null) warnings.push(`${activePoints} non-excluded source-backed data points are available.`);
  if (warnings.length) {
    lines.push('', '### Import Integrity Signals', '');
    for (const warning of warnings) lines.push(`- ${warning}`);
  }

  const computedQuality = buildComputedIntelQualityFilterContext({ limit: stagedLimit });
  if (computedQuality) lines.push('', computedQuality);

  if (hasTable('health_markers') && hasColumn('health_markers', 'auto_created')) {
    const qualityLookup = {
      canonicalIds: markerCanonicalIdMap(),
      markersById: new Map(allIntelMarkers().map(marker => [marker.id, marker])),
      dataByRawMarker: listDataPointsGroupedByMarker(db),
    };
    const autoRows = db.prepare(`
      SELECT
        m.id,
        m.name,
        m.unit,
        m.group_id,
        m.ref_low,
        m.ref_high,
        m.target,
        m.auto_created,
        COUNT(h.id) AS points,
        MIN(h.date) AS first_date,
        MAX(h.date) AS latest_date,
        (
          SELECT h2.value
          FROM health_data_points h2
          WHERE h2.marker_id = m.id AND h2.excluded = 0
          ORDER BY h2.date DESC, h2.id DESC
          LIMIT 1
        ) AS latest_value
      FROM health_markers m
      LEFT JOIN health_data_points h ON h.marker_id = m.id AND h.excluded = 0
      WHERE COALESCE(m.auto_created, 0) = 1
      GROUP BY m.id
      ORDER BY points DESC, latest_date DESC, m.name ASC
      LIMIT ?
    `).all(autoLimit);
    if (autoRows.length) {
      lines.push('', '### Auto-Created Marker Review Queue', '');
      lines.push('These markers came from imports before manual ontology curation. Use their values, but treat labels/groups/reference ranges as review-needed unless corroborated elsewhere.');
      for (const row of autoRows) {
        const ref = [
          row.ref_low != null ? `low ${row.ref_low}` : null,
          row.ref_high != null ? `high ${row.ref_high}` : null,
          row.target != null ? `target ${row.target}` : null,
        ].filter(Boolean).join(', ');
        const { marker, point } = latestVisibleIntelPointForMarkerId(row.id, qualityLookup);
        const displayUnit = marker?.unit || row.unit || '';
        const latest = point?.date
          ? `latest ${point.value} ${displayUnit} on ${point.date}`
          : row.points
            ? 'all active values currently filtered by chart-grade quality rules'
            : 'no active data';
        lines.push(`- ${row.name} (${row.id}, ${healthMarkerReviewContext(row)}): ${row.points} point${row.points === 1 ? '' : 's'}, ${latest}${ref ? `, ref ${ref}` : ''}`);
      }
    }
  }

  const reasonRows = db.prepare(`
    SELECT source, COALESCE(NULLIF(exclude_reason, ''), 'unspecified') AS reason, COUNT(*) AS count
    FROM health_data_points
    WHERE excluded = 1
    GROUP BY source, reason
    ORDER BY count DESC, source ASC, reason ASC
    LIMIT ?
  `).all(stagedLimit);
  if (reasonRows.length) {
    lines.push('', '### Excluded Data Point Reasons', '');
    for (const row of reasonRows) {
      lines.push(`- ${row.source || 'unknown'}: ${row.count} excluded (${row.reason})`);
    }
  }

  if (hasTable('fhir_staged_observations')) {
    const stagedRows = db.prepare(`
      SELECT status, COALESCE(NULLIF(reason, ''), 'unspecified') AS reason, COUNT(*) AS count
      FROM fhir_staged_observations
      GROUP BY status, reason
      ORDER BY count DESC, status ASC, reason ASC
      LIMIT ?
    `).all(stagedLimit);
    if (stagedRows.length) {
      lines.push('', '### Staged FHIR Observation Review', '');
      for (const row of stagedRows) {
        lines.push(`- ${row.status}: ${row.count} observation${row.count === 1 ? '' : 's'} (${row.reason})`);
      }
    }

    const topNames = db.prepare(`
      SELECT fhir_display_name, status, COUNT(*) AS count
      FROM fhir_staged_observations
      WHERE status IN ('pending', 'excluded')
      GROUP BY fhir_display_name, status
      ORDER BY count DESC, fhir_display_name ASC
      LIMIT ?
    `).all(stagedLimit);
    if (topNames.length) {
      lines.push('', '### Top Staged Names', '');
      for (const row of topNames) {
        lines.push(`- ${row.fhir_display_name}: ${row.count} ${row.status}`);
      }
    }
  }

  return lines.length > 3 ? lines.join('\n') : '';
}

function buildMedicationTimeline() {
  let meds = [];
  try {
    meds = listEffectiveMedicationsRaw(db);
  } catch {
    meds = [];
  }
  const rows = meds
    .filter(m => m.date_started || m.date_stopped || m.status || m.notes)
    .sort((a, b) => String(a.date_started || a.date_stopped || '9999').localeCompare(String(b.date_started || b.date_stopped || '9999')));
  if (!rows.length) return '';

  const lines = ['### Medication And Supplement Timeline', ''];
  for (const med of rows) {
    const dates = [
      med.date_started ? `started ${med.date_started}` : null,
      med.date_stopped ? `stopped ${med.date_stopped}` : null,
    ].filter(Boolean).join(', ') || 'date not available';
    const details = [med.dose, med.frequency, med.timing, med.status].filter(Boolean).join(' | ');
    lines.push(`- ${dates}: ${med.name}${details ? ` - ${details}` : ''}${med.notes ? ` - ${med.notes}` : ''}`);
  }
  return lines.join('\n');
}

function buildHealthTimelineEvents({ limit = 80, mode = 'clinical' } = {}) {
  if (!hasTable('timeline_events')) return '';
  const historyMode = mode === 'history';
  const likeClauses = historyMode
    ? [
      'history', 'family', 'diagnos', 'procedure', 'surgery', 'symptom',
      'flare', 'medication', 'started', 'stopped', 'dose', 'olumiant',
      'humira', 'chlorthalidone', 'rosuvastatin', 'ezetimibe', 'behcet',
      'alopecia', 'kidney', 'stone', 'calcium', 'nutrition', 'diet', 'food',
      'supplement', 'apoe', 'lipid', 'autoimmune', 'inflammation', 'dexa',
      'fracture', 'sleep', 'exposure'
    ]
    : [
      'health', 'medical', 'lab', 'blood', 'cholesterol', 'apob', 'ldl', 'oura',
      'sleep', 'olumiant', 'humira', 'chlorthalidone', 'rosuvastatin',
      'ezetimibe', 'behcet', 'alopecia', 'kidney', 'stone', 'calcium',
      'nutrition', 'diet', 'food', 'supplement'
    ];
  const healthSourcePredicate = historyMode
    ? "(source_type IN ('health', 'user') AND COALESCE(event_type, '') NOT IN ('lab_draw', 'lab_result', 'health_metric'))"
    : "source_type IN ('health', 'user')";
  const whereSql = `${healthSourcePredicate}
       OR (${likeClauses.map(() => 'lower(summary) LIKE ?').join(' OR ')})`;
  const queryLimit = historyMode ? Math.max(limit * 8, 1200) : limit;
  const queryRows = (order) => db.prepare(`
    SELECT id, event_date, source_type, source_id, event_type, summary, metadata
    FROM timeline_events
    WHERE ${whereSql}
    ORDER BY event_date ${order}, id ${order}
    LIMIT ?
  `).all(...likeClauses.map(word => `%${word}%`), queryLimit);

  let rows = queryRows('ASC');
  if (historyMode) {
    rows = uniqueTimelineRows([...rows, ...queryRows('DESC')])
      .filter(row => !isRoutineLabTimelineRow(row))
      .sort((a, b) => String(a.event_date || '').localeCompare(String(b.event_date || '')) || String(a.id || '').localeCompare(String(b.id || '')));
  }
  if (!rows.length) return '';

  const lines = [historyMode ? '### Source Material Health Events' : '### Source Timeline Events', ''];
  const selected = historyMode ? selectFullSpanTimelineRows(rows, limit) : rows;
  if (historyMode && rows.length > selected.length) {
    const first = rows[0]?.event_date || 'unknown';
    const last = rows[rows.length - 1]?.event_date || 'unknown';
    lines.push(`Selected ${selected.length} representative material events across ${first} to ${last} from ${rows.length} source-backed candidates. Do not infer omitted details.`);
    lines.push('');
  }
  const outputRows = historyMode
    ? [...selected].sort((a, b) => String(b.event_date || '').localeCompare(String(a.event_date || '')) || String(b.id || '').localeCompare(String(a.id || '')))
    : selected;
  for (const row of outputRows) {
    const meta = safeJsonSummary(row.metadata);
    const origin = row.source_type === 'user' || String(row.event_type || '').includes('owner_attested') ? 'user' : 'import';
    lines.push(`- ${row.event_date}: [${origin}] [${row.source_type}/${row.event_type}] ${row.summary}${meta ? ` - ${meta}` : ''}`);
  }
  return lines.length > 2 ? lines.join('\n') : '';
}

function uniqueTimelineRows(rows) {
  const seen = new Set();
  const out = [];
  for (const row of rows || []) {
    const key = row.id || `${row.event_date}|${row.source_type}|${row.source_id}|${row.event_type}|${row.summary}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(row);
  }
  return out;
}

function selectFullSpanTimelineRows(rows, limit) {
  const sorted = [...(rows || [])].sort((a, b) => String(a.event_date || '').localeCompare(String(b.event_date || '')) || String(a.id || '').localeCompare(String(b.id || '')));
  if (!limit || sorted.length <= limit) return sorted;

  const selected = new Map();
  const keyFor = (row) => row.id || `${row.event_date}|${row.source_type}|${row.source_id}|${row.event_type}|${row.summary}`;
  const add = (row) => {
    if (!row || selected.size >= limit) return;
    selected.set(keyFor(row), row);
  };

  const edgeCount = Math.min(12, Math.floor(limit / 8));
  for (const row of sorted.slice(0, edgeCount)) add(row);
  for (const row of sorted.slice(-edgeCount)) add(row);

  const remaining = Math.max(0, limit - selected.size);
  for (let i = 0; i < remaining; i += 1) {
    const index = remaining <= 1
      ? Math.floor((sorted.length - 1) / 2)
      : Math.round((i * (sorted.length - 1)) / (remaining - 1));
    add(sorted[index]);
  }

  for (const row of sorted) {
    if (selected.size >= limit) break;
    add(row);
  }

  return [...selected.values()].sort((a, b) => String(a.event_date || '').localeCompare(String(b.event_date || '')) || String(a.id || '').localeCompare(String(b.id || '')));
}

function isRoutineLabTimelineRow(row) {
  const eventType = String(row.event_type || '').toLowerCase();
  const summary = String(row.summary || '').toLowerCase();
  return eventType.includes('lab')
    || eventType.includes('metric')
    || summary.startsWith('lab:')
    || /\b(latest|marker|result|value)\b/.test(summary);
}

function buildOwnerAttestedHealthHistory({ limit = 60 } = {}) {
  if (!hasTable('health_notes')) return '';
  let rows = [];
  try {
    rows = db.prepare(`
      SELECT id, date, content, tags, created_at
      FROM health_notes
      WHERE source = 'owner_attested_health_history'
      ORDER BY date ASC, id ASC
      LIMIT ?
    `).all(limit);
  } catch {
    return '';
  }
  if (!rows.length) return '';

  const lines = [
    '## Owner-Attested Health History - Tier 1 Raw Source',
    '',
    'Treat these entries as high-quality patient-provided history. Use them for synthesis, but preserve uncertainty when the raw text itself is uncertain.',
  ];
  for (const row of rows) {
    let tags = [];
    try { tags = JSON.parse(row.tags || '[]'); } catch {}
    lines.push(
      '',
      `### ${row.date} - health note ${row.id}`,
      `Created: ${row.created_at || 'unknown'}`,
      tags.length ? `Tags: ${tags.join(', ')}` : 'Tags: owner_attested',
      '',
      'BEGIN RAW OWNER-ATTESTED HISTORY',
      String(row.content || '').trim(),
      'END RAW OWNER-ATTESTED HISTORY',
    );
  }
  return lines.join('\n');
}

function buildLabBoundaryTimeline({ limit = 180 } = {}) {
  if (!hasTable('health_data_points') || !hasTable('health_markers')) return '';
  const rows = db.prepare(`
    SELECT h.date, h.value, m.id AS marker_id, m.name, m.unit, m.group_id, m.ref_low, m.ref_high, m.target
    FROM health_data_points h
    JOIN health_markers m ON m.id = h.marker_id
    WHERE h.excluded = 0
      AND (m.ref_low IS NOT NULL OR m.ref_high IS NOT NULL OR m.target IS NOT NULL)
    ORDER BY m.id ASC, h.date ASC
  `).all();
  if (!rows.length) return '';

  const events = [];
  let currentMarker = null;
  let previousStatus = null;
  let previousRow = null;
  for (const row of rows) {
    if (row.marker_id !== currentMarker) {
      currentMarker = row.marker_id;
      previousStatus = null;
      previousRow = null;
    }
    const status = valueStatus(row);
    const isBoundaryChange = previousStatus && status !== previousStatus;
    const isFirstOutOfRange = !previousStatus && status !== 'in range';
    if (isBoundaryChange || isFirstOutOfRange) {
      const ref = [
        row.ref_low != null ? `low ${row.ref_low}` : null,
        row.ref_high != null ? `high ${row.ref_high}` : null,
        row.target != null ? `target ${row.target}` : null,
      ].filter(Boolean).join(', ');
      const from = previousRow ? ` from ${previousStatus}` : '';
      events.push({
        date: row.date,
        line: `- ${row.date}: ${row.name} moved${from} to ${status} at ${row.value} ${row.unit || ''}${ref ? ` (ref ${ref})` : ''}`,
      });
    }
    previousStatus = status;
    previousRow = row;
  }
  events.sort((a, b) => a.date.localeCompare(b.date));
  const shown = events.slice(0, limit);
  if (!shown.length) return '';

  const lines = ['### Lab Boundary Crossings Across Available History', ''];
  if (events.length > shown.length) {
    lines.push(`Showing first ${shown.length} of ${events.length} source-backed boundary crossings. Use the yearly coverage table for the complete available date span.`);
    lines.push('');
  }
  for (const event of shown) lines.push(event.line);
  return lines.join('\n');
}

function buildStructuredHealthTimeline({ limit = 180, mode = 'clinical' } = {}) {
  const historyMode = mode === 'history';
  const sections = [
    historyMode ? '' : buildYearlyHealthCoverage(),
    buildMedicationTimeline(),
    buildHealthTimelineEvents({ limit: Math.min(limit, historyMode ? 160 : 100), mode }),
    historyMode ? '' : buildLabBoundaryTimeline({ limit }),
  ].filter(Boolean);
  if (!sections.length) return '';
  return historyMode ? [
    '## Structured Health Timeline - User-Reported, Family, and Material Events',
    '',
    'Use this as source material for the History tab. It intentionally excludes routine lab-value chronology. Lab values belong in History only when they explain a user-reported history item, family-risk interpretation, diagnosis, symptom, flare, medication/procedure decision, stone event, or other material clinical event.',
    '',
    ...sections,
  ].join('\n\n') : [
    '## Structured Health Timeline - Whole Available Patient History',
    '',
    'Use this as source material for the timeline tab. It covers the full available health data span and major source-backed changes; do not compress it to only recent events.',
    '',
    ...sections,
  ].join('\n\n');
}

function stripFrontmatter(text) {
  let value = String(text || '').trim();
  if (value.startsWith('---')) {
    const end = value.indexOf('\n---', 3);
    if (end !== -1) value = value.slice(end + 4).trim();
  }
  return value;
}

function readHistoricalHealthFile(label, path, maxChars) {
  try {
    if (!existsSync(path)) return '';
    const content = stripFrontmatter(readFileSync(path, 'utf8'));
    if (!content) return '';
    return `### ${label}\n\n${content.slice(0, maxChars)}`;
  } catch {
    return '';
  }
}

function escapeRegExp(text) {
  return String(text || '').replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function extractMarkdownSection(content, heading) {
  const value = String(content || '');
  const pattern = new RegExp(`(^|\\n)(##\\s+${escapeRegExp(heading)}[^\\n]*\\n[\\s\\S]*?)(?=\\n##\\s+|$)`, 'i');
  return value.match(pattern)?.[2]?.trim() || '';
}

function listMarkdownFiles(dir, limit = 12) {
  try {
    if (!existsSync(dir)) return [];
    const found = [];
    const walk = (current) => {
      for (const name of readdirSync(current).sort()) {
        const path = resolve(current, name);
        const stat = statSync(path);
        if (stat.isDirectory()) walk(path);
        else if (stat.isFile() && /\.md$/i.test(name)) found.push(path);
      }
    };
    walk(dir);
    return found.slice(-limit);
  } catch {
    return [];
  }
}

function readHistoricalHealthFolder(label, dir, { maxChars = 9000, maxFiles = 10 } = {}) {
  const files = listMarkdownFiles(dir, maxFiles);
  if (!files.length) return '';
  const lines = [`### ${label}`, ''];
  let remaining = maxChars;
  for (const path of files) {
    if (remaining <= 0) break;
    let content = '';
    try {
      content = stripFrontmatter(readFileSync(path, 'utf8')).trim();
    } catch {
      continue;
    }
    if (!content) continue;
    const header = `#### ${basename(path)}\n\n`;
    const slice = content.slice(0, Math.max(0, remaining - header.length)).trim();
    if (!slice) continue;
    lines.push(header + slice, '');
    remaining -= header.length + slice.length + 2;
  }
  return lines.length > 2 ? lines.join('\n') : '';
}

function buildRecoveredHealthProductMemory() {
  const archive = resolve(USER_MEMORY_DIR, 'archive');
  const files = [
    ['Health Intelligence Engine', 'project_health_intelligence.md', 2600],
    ['Health Dashboard V3 Memory', 'project_health.md', 2400],
    ['Pulse Health Command Center', 'project_pulse_command_center.md', 2600],
    ['Pulse Redesign Memory', 'project_pulse_redesign.md', 2200],
    ['Health Data Authority', 'feedback_health_data_authority.md', 1600],
    ['Health Opus Rule', 'feedback_health_opus.md', 1200],
    ['Pulse Chart Feedback', 'feedback_pulse_charts.md', 1600],
    ['Health Data Pipeline', 'project_health_data_pipeline.md', 1800],
  ];
  const sections = files
    .map(([label, file, maxChars]) => readHistoricalHealthFile(label, resolve(archive, file), maxChars))
    .filter(Boolean);
  if (!sections.length) return '';
  return [
    '### Recovered Health Product Memory',
    '',
    'These are older owner-approved health-app and intelligence memories. Use them as product/analysis operating instructions, not as current lab facts unless corroborated by structured data.',
    '',
    ...sections,
  ].join('\n\n');
}

function buildCanonicalHealthTopicContext(maxChars = 7000) {
  return readHistoricalHealthFile(
    'Canonical Health Topic Context',
    resolve(USER_CONTEXTS_DIR, 'topics/personal/health/context.md'),
    maxChars
  );
}

function buildImportedHealthVaultIndex(maxChars = 9000) {
  const path = resolve(USER_DATABASES_DIR, 'health/health.md');
  try {
    if (!existsSync(path)) return '';
    const content = stripFrontmatter(readFileSync(path, 'utf8'));
    if (!content) return '';
    const firstSectionAt = content.search(/\n##\s+/);
    const titleBlock = content.slice(0, firstSectionAt > 0 ? firstSectionAt : 900).trim();
    const sections = [
      extractMarkdownSection(content, 'Apple Health Clinical Records (Important)'),
      extractMarkdownSection(content, 'Known Missing Data'),
      extractMarkdownSection(content, 'Key Corrections Log'),
    ].filter(Boolean);
    const digest = [titleBlock, ...sections].filter(Boolean).join('\n\n');
    return `### Imported Health Vault Index\n\n${digest.slice(0, maxChars)}`;
  } catch {
    return '';
  }
}

function buildHistoricalHealthSubstrate(tab = 'intel') {
  const healthWk = resolve(USER_WORKBENCHES_DIR, 'topics/personal/health/wk_health');
  const healthContext = resolve(USER_CONTEXTS_DIR, 'topics/personal/health');
  const sessionFiles = readHistoricalHealthFolder(
    'Health Workbench Session Decisions',
    resolve(healthWk, 'substrate/sessions'),
    { maxChars: 11000, maxFiles: 12 }
  );
  const chronologyMode = tab === 'chronology';
  const candidates = chronologyMode
    ? [
      ['Canonical Health Topic Context', null, 1],
      ['Imported Health Vault Index', null, 1],
      ['Owner-Attested Health History', resolve(healthWk, 'substrate/owner-attested-history.md'), 12000],
      ['Medical Engineer Protocol', resolve(healthContext, 'framings/medical-engineer.md'), 4500],
      ['Health Workbench Session Decisions', null, 1],
      ['Health Synthesis', resolve(healthWk, 'SYNTHESIS.md'), 5000],
      ['Current Workbench Status', resolve(healthWk, 'SESSION-STATUS.md'), 4000],
      ['Legacy Health Context', resolve(healthWk, 'substrate/legacy-contexts/health-context-2026-05-12.md'), 3000],
      ['Recovered Health Product Memory', null, 1],
    ]
    : [
      ['Medical Engineer Protocol', resolve(healthContext, 'framings/medical-engineer.md'), 6000],
      ['Canonical Health Topic Context', null, 1],
      ['Owner-Attested Health History', resolve(healthWk, 'substrate/owner-attested-history.md'), 12000],
      ['Recovered Health Product Memory', null, 1],
      ['Health Workbench Session Decisions', null, 1],
      ['Current Workbench Status', resolve(healthWk, 'SESSION-STATUS.md'), 7000],
      ['Health Synthesis', resolve(healthWk, 'SYNTHESIS.md'), 9000],
      ['Health Index', resolve(healthWk, 'INDEX.md'), 2500],
      ['Legacy Health Context', resolve(healthWk, 'substrate/legacy-contexts/health-context-2026-05-12.md'), 3500],
      ['Imported Health Vault Index', null, 1],
    ];
  const sections = candidates
    .map(([label, path, maxChars]) => {
      if (label === 'Canonical Health Topic Context') return buildCanonicalHealthTopicContext(chronologyMode ? 7000 : 4500);
      if (label === 'Imported Health Vault Index') return buildImportedHealthVaultIndex(chronologyMode ? 9000 : 4500);
      if (label === 'Recovered Health Product Memory') return buildRecoveredHealthProductMemory();
      if (label === 'Health Workbench Session Decisions') return sessionFiles;
      return readHistoricalHealthFile(label, path, maxChars);
    })
    .filter(Boolean);
  if (!sections.length) return '';
  return '## Historical Health Substrate (local workbench + imported health file)\n\n' + sections.join('\n\n');
}

export async function buildHealthContext(options = {}) {
  const tab = options.tab && CONTEXT_PROFILES[options.tab] ? options.tab : 'insights';
  const profile = { ...CONTEXT_PROFILES[tab], ...(options.profile || {}) };
  const sections = [];

  try {
    const memory = await buildAppMemoryContext({
      app: 'health',
      topic: 'health',
      tier: 'workbench',
      maxChars: profile.memoryChars,
    });
    if (memory) sections.push(memory);
  } catch { /* memory continuity unavailable — continue with structured data */ }

  // Inject health topic context_md first — contains the user's medical model,
  // primary thesis, reasoning protocol, and confirmed diagnoses. Sourced from
  // user_topics.context_md so it evolves as their health understanding grows.
  try {
    const row = db.prepare(
      "SELECT context_md FROM user_topics WHERE slug = 'health' AND context_md IS NOT NULL AND length(context_md) > 0"
    ).get();
    if (row?.context_md) {
      let ctx = row.context_md.trim();
      if (ctx.startsWith('---')) {
        const end = ctx.indexOf('\n---', 3);
        if (end !== -1) ctx = ctx.slice(end + 4).trim();
      }
      ctx = ctx.slice(0, profile.topicChars);
      if (ctx) sections.push(ctx);
    }
  } catch { /* context unavailable — continue with structured data */ }

  const historical = capSection(buildHistoricalHealthSubstrate(tab), profile.historicalChars, 'Historical health substrate');
  if (historical) sections.push(historical);

  const ownerHistory = capSection(
    buildOwnerAttestedHealthHistory({ limit: tab === 'chronology' ? 80 : 50 }),
    profile.ownerHistoryChars,
    'Owner-attested health history'
  );
  if (ownerHistory) sections.push(ownerHistory);

  const dataQuality = capSection(
    buildHealthDataQualityContext(),
    profile.dataQualityChars,
    'Health data quality and import coverage'
  );
  if (dataQuality) sections.push(dataQuality);

  if (tab === 'diet' || tab === 'insights') {
    const foodOntology = capSection(formatFoodOntology(), profile.foodChars, 'Health food ontology');
    if (foodOntology) sections.push(foodOntology);
  }

  if (tab !== 'chronology') {
    const labs = capSection(buildLatestLabsSummary({ limit: profile.labLimit }), profile.labChars, 'Latest lab summary');
    if (labs) sections.push('## Health Data (from structured database — exact latest lab/clinical values)\n\n' + labs);
    const nonLabSignals = capSection(
      buildNonLabSignalsSummary({ limit: profile.nonLabLimit || 40 }),
      profile.nonLabChars || 3200,
      'Non-lab clinical, wearable, and user-tracked signals'
    );
    if (nonLabSignals) sections.push('## Non-Lab Signals (context, not lab evidence)\n\n' + nonLabSignals);
  }

  const meds = buildActiveMeds();
  if (meds) sections.push(meds);

  const ui = getUIConfig();

  if (ui.conditionGroups?.length) {
    const conditions = ui.conditionGroups.map(g => `- **${g.name}**: ${g.desc}`).join('\n');
    sections.push(`## Health Ontology — Condition Groups\n\n${conditions}`);
  }

  if (ui.bodyAreaMap && Object.keys(ui.bodyAreaMap).length) {
    const areas = Object.entries(ui.bodyAreaMap)
      .map(([, v]) => `- **${v.name}**: ${v.context}`)
      .join('\n');
    sections.push(`## Health Ontology — Body Area Context\n\n${areas}`);
  }

  if (ui.rxGroups?.length) {
    const rxGroups = ui.rxGroups.map(g => {
      const status = g.status ? ` [${g.status}]` : '';
      const dose = g.dose ? ` ${g.dose}.` : '';
      return `- **${g.name}**${status}: ${dose} ${g.desc}`.replace(/\s+/g, ' ').trim();
    }).join('\n');
    sections.push(`## Health Ontology — Medication Groups\n\n${rxGroups}`);
  }

  if (['insights', 'intel', 'rx', 'nextvisit', 'chronology'].includes(tab)) {
    const timeline = capSection(
      buildStructuredHealthTimeline({
        limit: tab === 'chronology' ? 220 : 90,
        mode: tab === 'chronology' ? 'history' : 'clinical',
      }),
      profile.timelineChars,
      'Structured health timeline'
    );
    if (timeline) sections.push(timeline);
  }

  if (tab !== 'chronology') {
    const trends = capSection(buildMarkerTrends({ limit: profile.trendLimit }), profile.trendChars, 'Marker trends');
    if (trends) sections.push(trends);
  }

  return sections.join('\n\n');
}

// ─── Tab-specific system prompts ──────────────────────────────────────────

const IDENTITY_PREFIX = `You are the user's Medical Engineer. Today's date: ${new Date().toISOString().split('T')[0]}.
Medical Engineer protocol: root cause first. N=1 data beats population advice. Raw values beat prior summaries. Do not invent facts. If missing, write None.
Punchy memo. Conclusion first. At most 3 bullets per section. Define a jargon word once, in plain English, then the number.
Write each bullet as a short sentence a person can read aloud. No stacked codes, slashes, or parenthetical date strings. Put one fact per bullet. Name the month only when the date changes the decision (stale lab, a restart, a hold). Skip the date when the value is the current known reading.
Timeline events marked [user] are owner-supplied; [import] came from data. Do not mix them.
The operator can ask chat for more detail — do not write essays.`;

const TAB_PROMPTS = {
  insights: `${IDENTITY_PREFIX}

Write one Insights page from provided facts only. Use exactly these headings:

## Current State
One sentence verdict, then ≤3 evidence bullets in prose.

## Risk
≤4 bullets. Name the domain, say if it is active, then the one number that matters. Prose, not a table.

## Diet
What to eat and avoid, from the food ontology. ≤5 short sentences. Name the live rules (fat choices, spinach, almond flour, Citrus Squeeze, Clothe the Carbs) only if they are in context.

## Rx
Current regimen only. Held or stopped drugs are not active. ≤5 short sentences. Include dose if present.

## Next Visit
The 3 decisions worth the appointment, each as a sentence. None if nothing is pending.

## Watch
Markers to watch. One sentence each: what it is, the latest value, and a date only if it is stale or turning. ≤4 bullets.

No History section. No tables. No nested bullets. No "ALT 71 / AST 60 (2026-05-01)" packing. Write "ALT, the liver enzyme, is 71, last drawn in May."`,

  intel: `${IDENTITY_PREFIX}

Generate a world-class health command center from provided facts only. This tab is the executive state of the patient.

Use exactly:
## Current State
- 4-6 bullets. Each bullet must pair a conclusion with the strongest exact evidence available.
## Active Risk Map
| Domain | Status | Evidence | Mechanism | Next data |
Include cardiovascular/APOE4, autoimmune/inflammation, kidney stone/calcium, liver/Gilbert's, metabolic, sleep/recovery, and any other active ontology domain with evidence.
## Intervention Read
- Explain what appears to be working, what is unresolved, and what could be confounded.
## Watchlist
- Prioritized markers or symptoms to monitor. Include exact latest value/date/reference when present.
## Next Data Needed
- Concrete labs, measurements, or source checks that would change the decision.

If a detail is not in context, omit it or say "not available in provided context."`,

  diet: `${IDENTITY_PREFIX}

Generate the patient's personalized shopping and cooking guide from provided facts only.

The Health Food Ontology section is source material. Preserve its four-tier structure unless later context explicitly updates a food rule. This is custom guidance for the patient's documented lipid prevention, inflammatory, kidney-stone, metabolic, recovery, and brain-health drivers.
The rendered guide must carry the recovered ontology anchors: documented Tier 1 fat choices, raw spinach, almond-flour products, the Citrus Squeeze, and the Clothe the Carbs rule. If later context changes one of these rules, state the change and the source-backed reason.

Use exactly:
## Strategy
- 3-5 bullets tying the diet to the patient's actual drivers and latest available markers/context.
## Tier 1: Daily Staples (Unlimited)
Use the ontology categories: Proteins, Veggies, Fruits, Carbs, Fats and Oils, Nuts and Seeds, Snacks, Desserts. Add short patient-specific reason notes.
## Tier 2: Weekly Rotation (1-3x Week)
Use the ontology categories and explain the constraint/frequency.
## Tier 3: Allowable Exceptions (Managed Stress)
Use the ontology categories and state how to buffer these meals.
## Tier 4: Danger Zone (Avoid)
Use the ontology categories and tie each avoid group to inflammation, APOE4/saturated fat, stone/oxalate, or documented reactivity when supported.
## Chef's Narrative
Include Cold Start, Fat Buffer, Order of Operations, Clothe the Carbs, and Citrus Squeeze. Make these practical enough for someone cooking for the patient.
## Current Adjustments
- Any updates implied by latest provided labs, meds, calcium/stone context, or workbench decisions.
- If no update is supported, say which current patient drivers still preserve the baseline ontology: APOE4/lipid prevention, inflammation control, kidney-stone/calcium risk, metabolic stability, and brain health.

Do not add generic "healthy foods" outside the ontology unless the provided context explicitly supports them. Do not erase the four tiers.`,

  rx: `${IDENTITY_PREFIX}

Generate a medication and supplement intelligence tab from provided facts only.

The "Current Medications & Supplements" structured ledger is authoritative for current-use status. Do not describe a medication as active if that ledger says held, on_hold, stopped, or discontinued. Imported MedicationRequest records are prescriptions, not confirmed use.

Use exactly:
## Current Regimen
- Group prescriptions and supplements by timing and purpose. Include dose/frequency only when present.
## Mechanism Map
| Item | Why it is present | Markers/conditions it touches | What would prove it is helping |
## Monitoring
- Tie each monitoring item to exact lab values/dates, medication risk, or ontology domain when present.
## Interaction / Contraindication Watch
- Include immune suppression, lipid therapy, calcium/stone, liver, and supplement interactions only when supported.
## Protocol Gaps
- Missing dose/timing/start-date/monitoring facts that matter for safety or interpretation.
## Clinician Questions
- Specific questions that would change management.

Do not recommend medication changes without clinician approval.`,

  nextvisit: `${IDENTITY_PREFIX}

Generate a next-visit prep tab from provided facts only. This should be useful in the room with a clinician.

Use exactly:
## Decision Agenda
- The 3-6 decisions the visit should answer.
## Tests To Consider
| Test/panel | Why it matters | Triggering evidence | Decision it changes |
Include exact values/dates when present.
## Discussion Topics
- Group by clinician/specialist when supported.
## Questions To Ask
- Specific, non-generic questions tied to values, meds, symptoms, conditions, or protocol gaps.
## Bring
- Source material, logs, or prior results needed to make the visit productive.

Do not fabricate visits, diagnoses, symptoms, or overdue status.`,

  chronology: `${IDENTITY_PREFIX}

Generate the History tab from provided facts only. This is user history, family history, and material clinical history, not a lab chronology.

Use exactly:
## User-Reported History
- Patient-reported history from owner-attested entries and workbench context. Prioritize direct raw history over inferred events.
## Family History
- Family history and inherited-risk context when present. If absent, write "No family history available in provided context."
## Material Health Events
- Reverse-chronological bullets covering diagnoses, symptoms/flares, procedures, imaging/DEXA, medication starts/stops/dose changes, stone/calcium events, major diet protocol decisions, exposures, sleep/recovery turning points, and workbench clinical decisions.

Rules:
- Do not include any other top-level sections. In particular, do not output Memory Continuity, next-session anchors, source diagnostics, or workbench metadata as a separate section.
- Cover the full available patient history from the earliest source-backed history to today.
- Keep Material Health Events as one flat reverse-chronological bullet list. Do not add year subheadings, tables, or extra ### sections.
- Labs belong in History only when they explain a user-reported history item, family-risk interpretation, diagnosis, symptom, flare, medication/procedure decision, stone event, or other material clinical event.
- Do not list serial lab values, latest marker values, routine in-range labs, or standalone boundary crossings.
- If a period has dense lab data but no material history event, do not summarize the labs just to fill the period.
- Include explicit patient corrections when present, especially imported medication records that are prescriptions rather than confirmed actual use, prescribed-but-not-taken medications, wrong medication substitutions, or dose corrections.
- Preserve uncertainty: write "reason not available in provided context" when the causal reason is missing.

Do not limit to 10 events if the patient history contains more material events. Do not fabricate day-of-month, reason, family history, or event details.`,
};

/**
 * Return the tab-specific portion of the prompt (without the identity prefix).
 * Used by the UI to show the user what each tab asks the generation model for.
 */
export function getTabPrompt(tab) {
  const raw = TAB_PROMPTS[tab];
  if (!raw) return '';
  return raw.replace(IDENTITY_PREFIX, '').trim();
}

// ─── Generation ───────────────────────────────────────────────────────────

async function generateTabInternal(tab, customPrompt) {
  const basePrompt = customPrompt
    ? `${IDENTITY_PREFIX}\n\n${customPrompt}`
    : TAB_PROMPTS[tab];
  if (!basePrompt) throw new Error(`Unknown tab: ${tab}`);

  const healthContext = await buildHealthContext({ tab });
  if (!healthContext) {
    throw new Error('No health data available — import labs/meds before generating intel');
  }

  const systemPrompt = `${basePrompt}\n\n---\n\n${healthContext}`;
  const initialUserContent = tab === 'insights'
    ? 'Generate Insights. Use every required ## section. Keep it punchy. The operator will ask chat for more detail.'
    : `Generate the ${tab === 'nextvisit' ? 'next visit preparation' : tab} analysis. Include every exact required ## section from the system prompt, including the final section.`;
  const model = healthIntelModel();
  const billedUsage = { input_tokens: 0, output_tokens: 0 };
  const requestContent = async (userContent, label) => {
    const resp = await llmCreate({
      model,
      max_tokens: maxOutputTokensForTab(tab),
      timeout_ms: HEALTH_INTEL_TIMEOUT_MS,
      system: systemPrompt,
      messages: [{ role: 'user', content: userContent }],
    }, label);
    billedUsage.input_tokens += Number(resp.usage?.input_tokens) || 0;
    billedUsage.output_tokens += Number(resp.usage?.output_tokens) || 0;
    const rawContent = resp.content
      .filter(b => b.type === 'text')
      .map(b => b.text)
      .join('');
    return { resp, content: normalizeIntelGeneratedContent(tab, rawContent) };
  };

  let { resp, content } = await requestContent(initialUserContent, `health-intel-${tab}`);

  if (!content) throw new Error(`Empty response from model for tab: ${tab}`);
  let missing = missingIntelContentRequirements(tab, content);
  if (missing.length) {
    const retryUserContent = [
      `Regenerate the complete ${tab === 'nextvisit' ? 'next visit preparation' : tab} analysis from scratch.`,
      `The previous draft failed the required section contract: ${missing.join('; ')}.`,
      'Use every exact required ## section from the system prompt, including the final section. Do not omit empty sections; write a source-grounded bullet that says what is not available when needed.',
    ].join('\n');
    ({ resp, content } = await requestContent(retryUserContent, `health-intel-${tab}-contract-retry`));
    if (!content) throw new Error(`Empty response from model for tab: ${tab}`);
    missing = missingIntelContentRequirements(tab, content);
    if (missing.length) {
      throw new Error(`Generated ${tab} failed health intel contract: ${missing.join('; ')}`);
    }
  }

  let outputIssues = intelOutputCompletenessIssues(tab, content, { outputTokens: resp.usage?.output_tokens });
  if (outputIssues.length) {
    const retryUserContent = [
      `Regenerate the complete ${tab === 'nextvisit' ? 'next visit preparation' : tab} analysis from scratch.`,
      `The previous draft was unusable because it hit the output ceiling: ${outputIssues.join('; ')}.`,
      'Be more concise, but include every exact required ## section from the system prompt and finish with a complete final sentence.',
    ].join('\n');
    ({ resp, content } = await requestContent(retryUserContent, `health-intel-${tab}-budget-retry`));
    if (!content) throw new Error(`Empty response from model for tab: ${tab}`);
    missing = missingIntelContentRequirements(tab, content);
    outputIssues = intelOutputCompletenessIssues(tab, content, { outputTokens: resp.usage?.output_tokens });
    if (missing.length || outputIssues.length) {
      throw new Error(`Generated ${tab} failed health intel completion contract: ${[...missing, ...outputIssues].join('; ')}`);
    }
  }

  const savedModel = resp.model || model;
  saveIntelContent(tab, content, savedModel, billedUsage);
  console.info(
    `[health-intel] Generated ${tab} (${content.length} chars, ` +
    `${billedUsage.input_tokens || '?'}in/${billedUsage.output_tokens || '?'}out, ${savedModel})`
  );

  return { content, usage: billedUsage, model: savedModel };
}

/**
 * Regenerate a single tab. Optionally pass a custom instruction block to
 * override the built-in tab prompt (used for one-off exploratory queries).
 */
export async function regenerateTab(tab, customPrompt = null) {
  return generateTabInternal(tab, customPrompt);
}

/**
 * Public entry points for the 5 tabs. Thin wrappers so callers can import
 * the generator they want by name rather than juggling strings.
 */
export const generateInsights = () => generateTabInternal('insights', null);
export const generateIntel = () => generateTabInternal('insights', null);
export const generateDiet = () => generateTabInternal('insights', null);
export const generateRx = () => generateTabInternal('insights', null);
export const generateNextVisit = () => generateTabInternal('insights', null);
export const generateChronology = () => generateTabInternal('insights', null);

// ─── Regeneration jobs ───────────────────────────────────────────────────

let _regenJob = null;
let _queuedRegen = null;

function nowIso() {
  return new Date().toISOString();
}

function makeJobId() {
  return `health-intel-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function normalizeJobTabs(tabs = TABS) {
  const selected = [];
  for (const tab of tabs || []) {
    if (TABS.includes(tab) && !selected.includes(tab)) selected.push(tab);
  }
  if (!selected.length) throw new Error('No valid health intel tabs requested');
  return selected;
}

function unionTabs(left = [], right = []) {
  const selected = [];
  for (const tab of [...left, ...right]) {
    if (TABS.includes(tab) && !selected.includes(tab)) selected.push(tab);
  }
  return selected;
}

export function usageCostUsd(model, usage) {
  return estimateCostCents(model, Number(usage?.input_tokens) || 0, Number(usage?.output_tokens) || 0) / 100;
}

function addJobSpend(job, model, usage) {
  const usd = usageCostUsd(model, usage);
  job.spent_usd = Number(((Number(job.spent_usd) || 0) + usd).toFixed(6));
  return usd;
}

function jobAtSpendCap(job) {
  const cap = Number(job?.spend_cap_usd);
  return Number.isFinite(cap) && cap > 0 && (Number(job.spent_usd) || 0) >= cap;
}

function jobSnapshot(job = _regenJob) {
  if (!job) return null;
  const copy = JSON.parse(JSON.stringify(job));
  const tabs = copy.tabs || [];
  const ok = tabs.filter(t => t.status === 'ok').length;
  const error = tabs.filter(t => t.status === 'error').length;
  const running = tabs.filter(t => t.status === 'running').length;
  const pending = tabs.filter(t => t.status === 'pending').length;
  copy.progress = {
    total: tabs.length,
    ok,
    error,
    running,
    pending,
    done: ok + error,
  };
  if (job === _regenJob && _queuedRegen) {
    copy.queued_recalculation = true;
    copy.queued_reason = _queuedRegen.reason;
    copy.queued_tabs = _queuedRegen.tabs;
  }
  return copy;
}

/**
 * The generated chart-copy step of a full recalc (st_3ca30b26).
 *
 * WHY it is a step on the job and not a sixth entry in TABS: TABS is a closed
 * constant that routes a name through generateTabInternal, which throws on a
 * name with no TAB_PROMPTS entry, runs two section validators against prose
 * that has no sections, and would add a sixth user-facing tab. Chart copy is a
 * different generator with a different model and a different output contract.
 */
async function runMarkerCopyStep(job) {
  job.marker_copy = { status: 'running', started_at: nowIso(), completed_at: null, error: null };
  try {
    const stats = await regenerateHealthMarkerCopy(db, {});
    job.marker_copy = { ...job.marker_copy, ...stats, status: 'ok', completed_at: nowIso() };
  } catch (err) {
    job.marker_copy = { ...job.marker_copy, status: 'error', error: err.message, completed_at: nowIso() };
    console.error('[health-intel] Failed to regenerate health marker copy:', err.message);
  }
  return job.marker_copy.status === 'ok';
}

async function runIntelRegenerationJob(job) {
  console.info(`[health-intel] Starting regeneration job ${job.id} (${job.reason})...`);
  for (const tabState of job.tabs) {
    if (jobAtSpendCap(job)) {
      tabState.status = 'capped';
      tabState.error = `spend cap $${Number(job.spend_cap_usd).toFixed(2)} reached`;
      job.results[tabState.tab] = { status: 'capped', error: tabState.error };
      continue;
    }
    tabState.status = 'running';
    tabState.started_at = nowIso();
    job.current_tab = tabState.tab;
    try {
      const { content, usage, model } = await generateTabInternal(tabState.tab, null);
      tabState.status = 'ok';
      tabState.length = content.length;
      tabState.usage = usage || null;
      tabState.model = model || null;
      addJobSpend(job, model, usage);
      job.results[tabState.tab] = { status: 'ok', length: content.length, usage: usage || null, model: model || null };
    } catch (err) {
      tabState.status = 'error';
      tabState.error = err.message;
      job.results[tabState.tab] = { status: 'error', error: err.message };
      console.error(`[health-intel] Failed to generate ${tabState.tab}:`, err.message);
    } finally {
      tabState.completed_at = nowIso();
    }
  }

  // Chart copy runs after the tabs, inside the same job, so one recalc press
  // refreshes the intelligence tabs AND the per-chart copy.
  let copyFailed = false;
  if (job.include_marker_copy && jobAtSpendCap(job)) {
    job.marker_copy = {
      ...(job.marker_copy || {}),
      status: 'capped',
      error: `spend cap $${Number(job.spend_cap_usd).toFixed(2)} reached`,
      completed_at: nowIso(),
    };
  } else if (job.include_marker_copy) copyFailed = !(await runMarkerCopyStep(job));

  const failed = job.tabs.some(t => t.status === 'error') || copyFailed;
  const capped = job.tabs.some(t => t.status === 'capped') || job.marker_copy?.status === 'capped';
  job.status = failed ? 'error' : capped ? 'capped' : 'complete';
  job.current_tab = null;
  job.completed_at = nowIso();
  console.info(`[health-intel] Regeneration job ${job.id} ${job.status}:`, JSON.stringify(job.results));
  if (_regenJob === job && _queuedRegen) {
    const queued = _queuedRegen;
    _queuedRegen = null;
    startIntelRegenerationJob({
      tabs: queued.tabs,
      reason: `${queued.reason}_queued_after_${job.status}`,
      includeMarkerCopy: queued.includeMarkerCopy,
      spendCapUsd: queued.spendCapUsd,
    });
  }
}

export function getIntelRegenerationJob() {
  return jobSnapshot();
}

export function startIntelRegenerationJob({ tabs = TABS, reason = 'manual', includeMarkerCopy = false, spendCapUsd = null } = {}) {
  const selected = normalizeJobTabs(tabs);
  const cap = Number(spendCapUsd);
  const spendCap = Number.isFinite(cap) && cap > 0 ? cap : null;
  if (_regenJob?.status === 'running') {
    _queuedRegen = {
      tabs: unionTabs(_queuedRegen?.tabs || [], selected),
      reason,
      requested_at: nowIso(),
      // Once any queued request wants chart copy, the coalesced run does too.
      includeMarkerCopy: Boolean(_queuedRegen?.includeMarkerCopy) || Boolean(includeMarkerCopy),
      spendCapUsd: spendCap ?? _queuedRegen?.spendCapUsd ?? null,
    };
    return { job: jobSnapshot(_regenJob), alreadyRunning: true, queued: true };
  }

  _regenJob = {
    id: makeJobId(),
    reason,
    status: 'running',
    started_at: nowIso(),
    completed_at: null,
    current_tab: null,
    include_marker_copy: Boolean(includeMarkerCopy),
    spend_cap_usd: spendCap,
    spent_usd: 0,
    marker_copy: Boolean(includeMarkerCopy) ? { status: 'pending' } : null,
    tabs: selected.map(tab => ({
      tab,
      status: 'pending',
      started_at: null,
      completed_at: null,
      length: null,
      usage: null,
      error: null,
    })),
    results: {},
    error: null,
  };

  const job = _regenJob;
  setTimeout(() => {
    runIntelRegenerationJob(job).catch(err => {
      job.status = 'error';
      job.error = err.message;
      job.current_tab = null;
      job.completed_at = nowIso();
      console.error('[health-intel] Regeneration job crashed:', err);
    });
  }, 0);

  return { job: jobSnapshot(_regenJob), alreadyRunning: false };
}

/**
 * Regenerate every tab sequentially. Sequential (not parallel) so provider rate
 * limits don't bite and so a single failure doesn't kill the batch.
 * Called after a health data import or a maintenance pass.
 */
export async function regenerateAllIntel() {
  console.info('[health-intel] Regenerating all intel tabs...');
  const results = {};
  for (const tab of TABS) {
    try {
      const { content } = await generateTabInternal(tab, null);
      results[tab] = { status: 'ok', length: content.length };
    } catch (err) {
      console.error(`[health-intel] Failed to generate ${tab}:`, err.message);
      results[tab] = { status: 'error', error: err.message };
    }
  }
  console.info('[health-intel] Regeneration complete:', JSON.stringify(results));
  return results;
}

/**
 * Read-only check that the module can be used — Anthropic key configured
 * and at least one health data point present. Used by the route layer to
 * return a clean error instead of crashing inside the SDK call.
 */
export function intelReadiness() {
  const hasKey = !!config.anthropicKey;
  let hasData = false;
  try {
    hasData = !!stmts().hasAnyDataPoint.get();
  } catch {}
  return { hasKey, hasData };
}
